apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitea
spec:
  params:
    - name: envId
    - name: occupyId
    - name: firstAutoAgree
      default: "true"
    - name: canWait
      default: "refuse"
  workspaces:
  - name: envsReply
    readOnly: true
  steps:
    - name: await
      image: 10.1.40.43:5000/busybox:1.31
      script:
        curl="curl"
        function createIssue() {
          
        }
