apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
    - name: maven-settings
    - name: maven-local-repository
      mountPath: /root/.m2
    - name: source
  params:
    - name: cwd
      description: 项目pom路径, 相对于source卷
      default: ""
    - name: goals
      type: array
      description: maven goals to run
      default: [ package ]
    - name: output
      default: "false"
  results:
  - name: output
  steps:
    - name: mvn-goals
      image: 10.1.40.43:5000/gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)/$(params.cwd)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - "$(params.goals)"
