apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-b-env-deploy
spec:
  params:
  - name: work-id
    description: all-workspaces-pvc内唯一子目录,作为workspace根目录(伪pvc)
  - name: repo-url
    description: git仓库URL
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-ref
    description: git仓库SHA
  - name: version
    description: 当前程序版本 (仅指定版本时, 附加images信息 + issue-comment)
    default:
  - name: before-env
  - name: env
  - name: src-root
    description: 代码根目录
    default:  

  workspaces:
  - name: all-workspaces
    description: |
      workspace根, 提供独立path,成workspace, 供各PipelineRun执行
  - name: workspace
    description: |
      存储输入资源, 作为后续步骤的数据来源/结果数据
  - name: gitea-user-token


  tasks:
  - name: latest-pass
    taskRef:
      name: git-tag-laster-content
    params:
    - name: repo-url 
      value: $(params.repo-url)
    - name: repo-revision
      value: $(params.repo-ref)
    - name: pattern
      value: $(params.version)-$(params.before-env)-pass-

  - name: create-env-images
    runAfter:
    - latest-pass 
    conditions:
    - conditionRef: token
      params:
      - name: exists
        value: await
      - name: name
        value: $(params.env)-token
      - name: id
        value: $(params.repo-ref)
      - name: status
        value: Processing
    taskRef:
      name: tag-change-batch
    params:
    - name: images
      value: $(tasks.latest-pass.results.images)
    - name: tag
      value: $(params.version)-$(params.env)-$(tasks.latest-pass.results.sha)

  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(tasks.latest-pass.results.sha)
    - name: deleteExisting
      value: 'true'

  - name: await-env-deployed
    runAfter:
    - create-env-images
    - fetch-repo
    conditions:
    - conditionRef: await
      params:
      - name: name
        value: $(params.env)-token
      - name: id
        value: $(params.repo-ref)
      - name: expect
        value: Deployed
      - name: waitKeys
        value: Processing
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo
        - 冒烟测试

  - name: notify-env-deploy-result-git-tag
    runAfter:
    - await-env-deployed
    taskRef:
      name: git-tag
    params:
    - name: tag
      value: $(params.version)-$(params.env)-deployed
    - name: force
      value: "true"
    - name: msg
      value: $(tasks.latest-pass.results.images)
    workspaces:
    - name: workspace
      workspace: workspace

  - name: version-context
    taskSpec:
      volumes:
      - name: context
        configmap:
          name: pipeline-context
      steps:
      - image: busybox:1.31
        volumeMounts:
        - name: context
          mountPath: /volumes/context
        script: |
          cd /volumes/context
          echo -n $(cat id) > $(results.issue-id.path)
      results:
      - name: issue-id
  - name: notify-env-deploy-result-gitea
    runAfter:
    - await-env-deployed
    taskRef:
      name: gitea
    params:
    - name: cmd
      value: createComment
    - name: args
      value: |
        $(params.repo-full-name) $(tasks.version-context.results.issue-id) \
        '已部署到uat环境. 待测试完成后, 可以 "/pass uat" 或 "/fail uat" 通知测试结果'
    workspaces:
    - name: token
      workspace: gitea-user-token
      subPath: token

  - name: clean
    runAfter:
    - notify-env-deploy-result-git-tag
    - notify-env-deploy-result-gitea
    taskRef:
      name: reply
    params:
    - name: opt
      value: clean
    - name: name
      value: $(params.env)-token
