apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
  - name: work-id
    description: all-workspaces-pvc内唯一子目录,作为workspace根目录(伪pvc)
  - name: repo-url
    description: git仓库URL
#  - name: repo-full-name
  - name: repo-ref
    description: git仓库分支
  - name: src-root
    description: 代码根目录
    default:  

  workspaces:
  - name: all-workspaces
    description: |
      workspace根, 提供独立path,成workspace, 供各PipelineRun执行
  - name: workspace
    description: |
      存储输入资源, 作为后续步骤的数据来源/结果数据
  - name: mvn-settings
    description: |
      maven settings.xml
  - name: mvn-local-repo
    description: |
      maven 本地仓库

  tasks:
  - name: create-issue
    conditions:
    - conditionRef: auto-await
      params:
      - name: envId
        value: a
      - name: type
        value: end
      - name: emerg
        value: "true"
    taskRef:
      name: gitea
    params:
    - name: token
      value: d3fa2321d24ae8525a44e5c74897bc3cd17eea4a
    - name: cmd
      value: createIssue
    - name: args
      value: "root/uaa-zuul 'Hello Word!' '新建了一个工单\\n可以用添加一条工单,触发后续执行'" 

  - name: clean-src-pvc-path
    runAfter: ["create-issue"]
    workspaces:
    - name: all-workspaces
      workspace: all-workspaces
    params:
    - name: work-id
      value: $(params.work-id)
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - rm
        - $(workspaces.all-workspaces.path)/$(params.work-id)
        - -rf
      workspaces:
      - name: all-workspaces
      params:
      - name: work-id
---

