apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-a-auto
spec:
  params:
  - name: work-id
    description: all-workspaces-pvc内唯一子目录,作为workspace根目录(伪pvc)
  - name: repo-url
    description: git仓库URL
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-ref
    description: git仓库SHA
  - name: version
    description: 当前程序版本 (仅指定版本时, 附加images信息 + issue-comment)
    default:
  - name: src-root
    description: 代码根目录
    default:  

  workspaces:
  - name: all-workspaces
    description: |
      workspace根, 提供独立path,成workspace, 供各PipelineRun执行
  - name: workspace
    description: |
      存储输入资源, 作为后续步骤的数据来源/结果数据
  - name: mvn-settings
    description: |
      maven settings.xml
  - name: mvn-local-repo
    description: |
      maven 本地仓库
  - name: gitea-user-token


  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-ref)
    - name: deleteExisting
      value: 'true'

  - name: create-auto-test-images
    runAfter:
    - fetch-repo
    conditions:
    - conditionRef: token
      params:
      - name: exists
        value: fail
      - name: name
        value: auto-test-token
      - name: id
        value: $(params.repo-ref)
      - name: status
        value: Processing
    taskRef:
      name: kaniko-batch
    workspaces:
    - name: source
      workspace: workspace
    params:
    - name: dest-prefix
      value: "10.1.40.43:5000/busybox:"
    - name: dest-suffix
      value: $(params.repo-ref)

  - name: await-auto-test-deployed
    runAfter:
    - create-auto-test-images
    conditions:
    - conditionRef: await
      params:
      - name: name
        value: auto-test-token
      - name: id
        value: $(params.repo-ref)
      - name: expect
        value: Deployed
      - name: waitKeys
        value: Processing
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo
        - 冒烟测试

  - name: functional-testing
    runAfter:
    - await-auto-test-deployed
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo
        - 功能测试

  - name: stress-testing
    runAfter:
    - await-auto-test-deployed
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo
        - 压力测试

  - name: auto-test-success
    runAfter:
    - functional-testing
    - stress-testing
    taskRef:
      name: reply
    params:
    - name: opt
      value: clean
    - name: name
      value: auto-test-token

  - name: version-context
    runAfter:
    - auto-test-success
    conditions:
    - conditionRef: test
      params:
      - name: args
        value: 
        - $(params.version)
    taskSpec:
      volumes:
      - name: context
        configmap:
          name: pipeline-context
      steps:
      - image: busybox:1.31
        volumeMounts:
        - name: context
          mountPath: /volumes/context
        script: |
          cd /volumes/context
          echo -n $(cat id) > $(results.issue-id.path)
      results:
      - name: issue-id

  - name: notify-auto-test-result-git-tag
    runAfter:
    - version-context
    taskRef:
      name: git-tag
    params:
    - name: tag
      value: $(params.version)-auto-test-pass-
    - name: append
      value: "true"
    - name: msg
      value: |
        $(tasks.create-auto-test-images.results.image-names)
    workspaces:
    - name: workspace
      workspace: workspace
      
  - name: notify-auto-test-result-gitea
    runAfter:
    - version-context
    taskRef:
      name: gitea
    params:
    - name: cmd
      value: createComment
    - name: args
      value: |
        $(params.repo-full-name) $(tasks.version-context.results.issue-id) \
        '已通过自动测试, 可以 "/deploy-uat " 部署到手动测试环境'
    workspaces:
    - name: token
      workspace: gitea-user-token
      subPath: token

