apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ci
spec:
  params:
  - name: repo-ref
  - name: src-root
    description: 代码根目录
    default:  

  workspaces:
  - name: project 
    description: |
      存储输入资源, 作为后续步骤的数据来源/结果数据
  - name: mvn-settings
    description: |
      maven settings.xml
  - name: mvn-local-repo
    description: |
      maven 本地仓库

  tasks:
  - name: create-images
    taskRef:
      name: kaniko-batch
    workspaces:
    - name: source
      workspace: project 
    params:
    - name: dest-prefix
      value: "10.1.40.43:5000/busybox:"
    - name: dest-suffix
      value: $(params.repo-ref)

  - name: return
    taskSpec:
      steps:
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          echo '$(params.image-names)' > $(results.image-names.path)
      params:
      - name: image-names
      results:
      - name: image-names
    params:
    - name: image-names
      value: $(tasks.create-images.results.image-names)
