apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-wrapper
spec:
  params:
  - name: repo-url
    description: git仓库URL
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-ref
    description: git仓库SHA
  - name: version
    description: 当前项目版本
  - name: before-env
  - name: env

  - name: pipeline-name
  - name: pipeline-serviceaccountname
    default: ""
  - name: pipeline-serviceaccountnames
    default: "" 
  - name: pipeline-workspaces
    default: ""
  - name: pipeline-params
    default: ""

  - name: notify
    description: 通知内容 (将指定内容写入gitea-comment)
    default: ""

  workspaces:
  - name: project 
    description: 项目git根目录, 全局pipelinerun传递, 作为后续步骤的数据来源
  - name: gitea-user-token

  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: project 
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-ref)
    - name: deleteExisting
      value: 'true'

  - name: params
    runAfter:
    - fetch-repo
    taskSpec:
      workspaces:
      - name: project
      params:
      - name: commit
      - name: pattern
      results:
      - name: tag-commit
      - name: project-claim
      steps:
      - image: 10.1.40.43:5000/alpine/git:1.0.17
        workingDir: $(workspaces.project.path)
        script: |
          ln -sb $HOME/.ssh /root
          git fetch --tags
          git tag -l '$(params.pattern)' --format='%(object)' \
          | grep $(params.commit) 2>/dev/null | xargs echo -n > $(results.tag-commit.path)
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          echo -n $(workspaces.project.claim) > $(results.project-claim.path)
    workspaces:
    - name: project 
      workspace: project 
    params:
    - name: commit
      value: $(params.repo-ref)
    - name: pattern
      value: $(params.version)_$(params.env)_pass_$(params.repo-ref)

  - name: trigger
    conditions:
    - conditionRef: test
      params:
      - name: args
        value:
        - -z
        - $(tasks.params.results.tag-commit)
    taskRef:
      name: pipelinerun-apply
    params:
    - name: name
      value: $(context.pipelineRun.name)-trigger-$(params.pipeline-name)
    - name: spec
      value: |
        pipelineRef:
          name: $(params.pipeline-name)
        serviceAccountName: $(params.pipeline-serviceaccountname)
        serviceAccountNames:
        $(params.pipeline-serviceaccountnames)
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: $(tasks.params.results.project-claim)
        $(params.pipeline-workspaces)
        params:
        - name: repo-url
          value: $(params.repo-url)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: repo-ref
          value: $(params.repo-ref)
        - name: version
          value: $(params.version)
        - name: before-env
          value: $(params.before-env)
        - name: env
          value: $(params.env)
        $(params.pipeline-params)
    - name: return-task
      value: fetch-repo

  - name: create-tag
    taskRef:
      name: git-tag
    workspaces:
    - name: workspace
      workspace: project
    params:
    - name: tag
      value: $(params.version)_$(params.env)_pass_$(params.repo-ref)
    - name: msg
      value: $(tasks.trigger.results.output)

  - name: version-context
    runAfter:
    - create-tag 
    conditions:
    - conditionRef: test
      params:
      - name: args
        value:
        - $(params.notify)
    taskRef:
      name: gitea
    params:
    - name: cmd
      value: getIssueId
    - name: args
      value: root/test dddd
    workspaces:
    - name: token
      workspace: gitea-user-token
      subPath: token

  - name: notify
    taskRef:
      name: gitea
    params:
    - name: cmd
      value: createComment
    - name: args
      value: |
        $(params.repo-full-name) $(tasks.version-context.results.output) \
        '$(params.notify)'
    workspaces:
    - name: token
      workspace: gitea-user-token
      subPath: token
