apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-all-workspaces-pvc
spec:
  volumeName: pipeline-all-workspaces-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-all-workspaces-pv
spec:
  hostPath: 
    path: /tmp/path
    type: DirectoryOrCreate
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-mvn-repo-pvc
spec:
  volumeName: pipeline-mvn-repo-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-mvn-repo-pv
spec:
  hostPath: 
    path: /home/vagrant/pv/mvn
    type: DirectoryOrCreate
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
