apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envsReply
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - list
  - get
  - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envsReply
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: envsReply
subjects:
- kind: ServiceAccount
  name: default
