apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: await
spec:
  params:
    - name: envId
    - name: occupyId
    - name: firstAutoAgree
      default: "true"
    - name: canWait
      default: "refuse"
  workspaces:
  - name: envsReply
    readOnly: true
  steps:
    - name: await
      image: busybox:1.31
      script:
        occupyId=$(params.occupyId)
        firstAutoAgree=$(params.firstAutoAgree)
        canWait=$(params.canWait)
        envReply=$(workspaces.envsReply.path)/$(params.envId)

        function await() {
          echo await; 
          sleep 30;
          canPass;
        }

        function agree() {
          echo agree;
          exit;
        }

        function refuse() {
          echo refuse;
          exit 1;
        }

        function canPass() {
          content=$(head -n 1 $envReply);
          case $content in
            "" | , ) 
              if $firstAutoAgree; then
                agree;
              else
                await;
              fi
              ;;
            $occupyId,agree )  agree;;
            $occupyId,* )  refuse;;
            *,agree )
              if [[ $canWait != await ]]; then
                refuse;
              else
                await;
              fi
              ;;
            * ) await;;
          esac
        }

        canPass
