apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: auto-await
spec:
  params:
    - name: url
      default: https://kubernetes.default
    - name: envId
      description: 用以创建ConfigMap
    - name: type
      default: begin
    - name: emerg
      default: "false"
  check:
    image: lachlanevenson/k8s-kubectl
    script: |
        url=$(params.url)
        ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

        kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"


        function begin() {
          until $kubectl create configmap $(params.envId); do
            if [[ $(params.emerg) == 'true' ]]; then
              echo no-await, it\'s over
              exit 1
            fi
            sleep 30
          done
        }

        function end() {
          $kubectl delete configmap $(params.envId) || exit 0
        }

        $(params.type)
