apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: await
spec:
  params:
    - name: url
      default: https://kubernetes.default

    - name: name
      description: ConfigMap name
    - name: id

    - name: expect
      default: Success

    - name: waitKeys
      description: id相同 & expect存在时, 继续等待
      default: ""
    - name: emergKeys
      description: id不同 & expect相同时, 是否异常退出
      default: ""

    - name: clean
      default: "false"
    - name: interval
      default: "30"

  check:
    image: 10.1.40.43:5000/lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
        url=$(params.url)
        ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

        kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"


        function doAwait() {
          sleep $(params.interval)
        }
        function getStatus() {
          status=$($kubectl get configmap $(params.name) -o jsonpath={.data.id}---{.data.status} 2>&1)
        }
        function isIn() {
          local v=$1
          local settings=$2
          for _v in $settings; do
            if [[ $v == $_v  ]]; then
              return
            fi
          done
          return 1
        }
        function clean() {
          $kubectl delete configmap $(params.name)
        }

        function await() {
          while true; do
            if ! getStatus || [[ $status == --- ]]; then
              doAwait
              continue 
            fi

            id=${status%%-*}
            status=${status##*-}
            expect=$(params.expect)

            if [[ x$id != x$(params.id) ]]; then
              if isIn $status "$(params.emergKeys)"; then
                echo id not same, but in emergKeys, exit immediately
                exit 1
              fi
              echo id is same, and not in emergKeys, await next
              doAwait
              continue
            fi

            if isIn $status "$(params.waitKeys)"; then
              echo id is same, but in waitKeys, await next
              doAwait
              continue
            fi
            if [[ $status == $expect ]]; then
              echo is Expect
              if [[ $(params.clean) == true ]]; then
                clean
              fi
              exit 0
            else
              echo not Expect
              exit 1
            fi
          done
        }

        await 
