apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-tag
spec:
  workspaces:
  - name: workspace
    description: git项目

  params:
  - name: sub-directory
    description: 子目录, 含.git目录
    default: ""

  - name: tag
  - name: append
    description: 是否追加随机后缀
    default: "false"
  - name: force
    description: 是否先删除tag (忽略后缀)
    default: "false"

  - name: msg
    default: ""

  - name: user
    default: none
  - name: email
    default: none@no.user.com

  steps:
    - name: tag
      image: 10.1.40.43:5000/alpine/git:1.0.17
      workingDir: $(workspaces.workspace.path)/$(params.sub-directory)
      script: |
        ln -s $HOME/.ssh /root/.ssh

        git config --global user.email "$(params.email)"
        git config --global user.name "$(params.user)"

        if test '$(params.append)' == 'true'; then
          tag=$(params.tag)$(mktemp -u XXXXXX)
        else
          tag=$(params.tag)
        fi

        if test '$(params.force)' == 'true'; then
          git fetch --tags
          for i in $(git tag | grep '^$(params.tag)'); do
            git tag -d $i
            git push origin --delete $i || true
          done
        fi

        msg='$(params.msg)'

        git tag $tag ${msg:+-m "$msg"}
        git push origin $tag
