apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-tag-laster-content
spec:
  params:
  - name: repo-url
  - name: repo-revision
  - name: pattern

  results:
  - name: tag
  - name: sha
  - name: images

  volumes:
  - name: source
    emptyDir: {}

  steps:
    - name: search
      image: 10.1.40.43:5000/gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.15.2
      volumeMounts:
      - name: source
        mountPath: /volumes/source
      workingDir: /volumes/source

      securityContext:
        runAsUser: 0

      script: |
        /ko-app/git-init \
        -url "$(params.repo-url)" \
        -revision "$(params.repo-revision)" \
        -path . \
        -depth 1

        git fetch --tags

        pattern="^$(params.pattern)"

        tag=$(git tag --sort=creatordate | grep $pattern | tail -n 1)
        test -n "$tag"

        echo -n $tag > $(results.tag.path)
        git tag $tag -n 999 --format='%(objectname)' | xargs echo -n > $(results.sha.path)
        git tag $tag -n 999 --format='%(contents)' > $(results.images.path)
