apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitea
spec:
  workspaces:
  - name: token
    readOnly: true

  params:
    - name: gitea
      default: gitea-gitea-http
    - name: port
      default: "3000"

    - name: cmd
      description: createDeployKey / createIssue / createComment
    - name: args
      description: |
        传于gitea相应请求, 可支持循环
        createDeployKey:  repoFullName title key
        createIssue:  repoFullName title body assignees
        getIssueId:  repoFullName title
        createComment:  repoFullName issueId body

  results:
  - name: id

  volumes:
  - name: output
    emptyDir: {}

  steps:
    - name: jq
      image: 10.1.40.43:5000/stedolan/jq
      volumeMounts:
      - name: output
        mountPath: /volumes/output
      script: |
        cd /volumes/output
        cp /usr/local/bin/jq .

    - name: await
      image: 10.1.40.43:5000/curlimages/curl:7.71.1
      volumeMounts:
      - name: output
        mountPath: /volumes/output
      script: |
        export PATH=$PATH:/volumes/output

        function url() {
          method=$1
          path=$2
          host=$(params.gitea)
          port=$(params.port)
          token=$(cat $(workspaces.token.path))
          data=$3
        
          echo "curl -X $method http://$host:$port/api/v1$path?access_token=$token" \
                -H \"accept: application/json\" -H \"Content-Type: application/json\" \
                -d \'$data\' \
                -f
        }
        
        function createIssue() {
          repoFullName=$1
          title=$2
          body=$3
          assignees=$4  #(echo $3|sed 's|"|\\"|g')
          url=$(url POST /repos/$repoFullName/issues "{
                  \"title\": \"$title\",
                  \"body\": \"$body\", 
                  \"assignees\": [ $assignees ] }")
          sh -c "$url"
        }

        function getIssueId() {
          repoFullName=$1
          title=$2
          url=$(url GET /repos/$repoFullName/issues?type=issues&q=$title)
          res=$(sh -c "$url")

          if test $(echo $res | jq length) -eq 1; then
            res=$(echo $res | jq -r .[0])
            if test $(echo $res | jq -r .title) == $title; then
              echo $res
              return
            fi
          fi
          exit 1
        }
        
        function createComment() {
          repoFullName=$1
          issue=$2
          body=${3//\"/\\\"}
          url=$(url POST /repos/$repoFullName/issues/$issue/comments "{ \"body\": \"$body\" }")
          sh -c "$url"                                
        }
 
        function createDeployKey() {
          repoFullName=$1
          title=$2
          key=$3
          url=$(url POST /repos/$repoFullName/keys "{ \"title\": \"$title\", \"key\": \"$key\", \"read_only\": true }")
          sh -c "$url"
        }

        while read args; do
          if test -n "$args"; then
            eval $(params.cmd) $args | jq -r '.id' | xargs -I {} echo -n {}" " >> $(results.id.path) 
          else
            true
          fi
        done <<EOF
        $(params.args)
        EOF
