apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  workspaces:
  - name: source

  params:
  - name: context
    description: The build context used by Kaniko.
    default: ""
  - name: dockerfile
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: destination
    description: Name (reference) of the image to build.

  - name: insecure-registry
    default: 10.1.40.43:5000

  results:
  - name: image-digest
    description: Digest of the image just built.

  steps:
  - name: build-and-push
    image: 10.1.40.43:5000/gcr.io/kaniko-project/executor:latest
    workingDir: $(workspaces.source.path)
    command:
    - /kaniko/executor
    - --context=$(workspaces.source.path)/$(params.context)
    - --dockerfile=$(params.dockerfile)
    - --destination=$(params.destination)
    - --digest-file=$(results.image-digest.path)
    - --insecure-registry=$(params.insecure-registry)
    - --verbosity=trace
