apiVersion: v1
kind: ConfigMap
metadata:
  name: mvn-settings
data:
  settings.xml: |
   <?xml version="1.0" encoding="UTF-8"?>
   <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
     <servers>
       <server>
         <id>releases</id>
         <username>deployment</username>
         <password>deployment123</password>
       </server>
       <server>
         <id>Snapshots</id>
         <username>deployment</username>
         <password>deployment123</password>
       </server>
       <server>
         <id>Releases</id>
         <username>deployment</username>
         <password>deployment123</password>
       </server>
     </servers>    
     <profiles>
       <profile>  
         <id>public</id>
         <repositories>  
           <repository>  
             <id>public</id>   
             <url>http://113.140.81.67:9012/nexus/content/groups/public/</url>
             <releases>  
               <enabled>true</enabled>  
             </releases>  
             <snapshots>  
               <enabled>true</enabled>
               <updatePolicy>never</updatePolicy>
             </snapshots>  
           </repository>
         </repositories>  
       </profile>
       <profile>
         <id>sonar</id>
         <activation>
           <activeByDefault>true</activeByDefault>
         </activation>
         <properties>
           <sonar.host.url>http://sonarqube-sonarqube:9000</sonar.host.url>
         </properties>
       </profile>
     </profiles>
     <activeProfiles>
       <activeProfile>public</activeProfile>
     </activeProfiles>    
     <pluginGroups>
       <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
     </pluginGroups>    
   </settings>
