apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openssh-client
spec:
  params:
    - name: host
    - name: port
      default: "22"
    - name: user
      default: pipeline@user.com

  workspaces:
    - name: output

  steps:
    - name: create
      image: 10.1.40.43:5000/lgatica/openssh-client:latest
      script: |
        ssh-keyscan -p $(params.port) $(params.host) > $(workspaces.output.path)/known_hosts

        ssh-keygen -qN "" -C $(params.user) -f $(workspaces.output.path)/id_rsa
      
