apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envsReply
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - configmaps
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  resources:
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envsReply
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envsReply
subjects:
- kind: ServiceAccount
  name: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envsReply
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envsReply
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
