apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: token
spec:
  params:
    - name: url
      default: https://kubernetes.default

    - name: exists
      default: await
      description: continue / fail / await
    - name: interval
      default: "30"

    - name: name
      description: ConfigMap name
    - name: id
    - name: start
      default: ""
    - name: end
      default: ""
    - name: status
      default: Processing
  check:
    image: 10.1.40.43:5000/lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
        url=$(params.url)
        ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

        kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"



        function doCreate() {
          local start=$(params.start)
          start=${start:=$(date -Is)}
          result=$($kubectl create configmap $(params.name) \
                   --from-literal=id=$(params.id) \
                   --from-literal=start=${start} \
                   --from-literal=status=$(params.status) 2>&1)
        }
        function isExists() {
          echo $result | grep exists 1>/dev/null 
        }
        function doAwait() {
          sleep $(params.interval)
        }

        function create() {
          until doCreate; do
            if ! isExists; then
              echo create token error!
              exit 1
            fi

            case $(params.exists) in
              continue )
                 exit 0
                 ;;
              fail )
                 exit 1
                 ;;
              await )
                doAwait
                ;;
            esac
          done
        }

        
        create
