apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-chat
spec:
  serviceAccountName: trigger
  triggers:
  - name: pipeline
    interceptors:
    - cel:
        filter: |
          bool(body.secret.compareSecret("key","gitea-issue-secret"))
          && body.issue.user.login == "${ROBOT_NAME}"
          && has(body.action) && has(body.issue) && has(body.comment.body)
        overlays:
        - key: commandLine
          expression: |
            body.comment.body.trim().split("\r\n")[0].trim()
    - cel:
        filter: |
          body.commandLine.matches("^\\[[^]]+\\] ")
        overlays:
        - key: title
          expression: "body.issue.title"
        - key: content
          expression: "body.issue.body"
        - key: message
          expression: "body.comment.body"
        - key: command
          expression: 'body.commandLine.substring(1,body.commandLine.indexOf("]"))'
        - key: params
          expression: 'body.commandLine.substring(body.commandLine.indexOf("]")+1)'
    bindings:
    - ref: gitea-chat-params-binding
    template:
      name: gitea-chat
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-chat-params-binding
spec:
  params:
  - name: title
    value: $(body.title)
  - name: content
    value: $(body.content)
  - name: message
    value: $(body.message)
  - name: command
    value: $(body.command)
  - name: params
    value: $(body.params)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitea-chat
spec:
  params:
  - name: title
  - name: content
  - name: message
  - name: command
  - name: params
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: gc-$(uid)
    spec:
      pipelineRef:
        name: chat-$(params.command)
      serviceAccountName: pipeline
      params:
      - name: title
        value: $(params.title)
      - name: content
        value: $(params.content)
      - name: message
        value: $(params.message)
      - name: params
        value: $(params.params)
