apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${PURPOSE}-bp-promotion
spec:
  params:
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-url
    description: git仓库URL
  - name: repo-branch
    description: git仓库分支
  - name: repo-ref
    description: git仓库SHA
  - name: git-server
    description: git server host (如:http://localhost:30280)
  - name: src-root
    description: 代码根目录
    default: 

  tasks: