apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: env-pipeline
spec:
  serviceAccountName: trigger
  triggers:
  - name: env-pipeline
    bindings:
    - ref: parse-env
    template:
      name: env-pipeline
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: parse-env
spec:
  params:
  - name: env
    value: $(header.additional)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: env-pipeline
spec:
  params:
  - name: env
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: env-pipeline-$(params.env)-$(uid)
    spec:
      pipelineRef:
        name: env-pipeline-$(params.env)
