apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tt
spec:
  pipelineRef:
    name: pipeline
  workspaces:
  - name: all-workspaces
    persistentVolumeClaim:
      claimName: pipeline-all-workspaces-pvc
  - name: workspace
    persistentVolumeClaim:
      claimName: pipeline-all-workspaces-pvc
    subPath: test1234567
  - name: mvn-settings
    configmap:
      name: mvn-settings
  - name: mvn-local-repo
    persistentVolumeClaim:
      claimName: pipeline-mvn-repo-pvc
  params:
  - name: work-id
    value: test1234567
  - name: repo-url
    value: https://github.com/1449312219/uaa-zuul.git
  - name: repo-ref
    value: master
  - name: src-root
    value: api-gateway

