apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline
spec:
  serviceAccountName: trigger
  triggers:
  - name: pipeline
    bindings:
    - ref: parse-branch
    template:
      name: branch-pipeline
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: parse-branch
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: repo-ref
    value: $(body.sha)
  - name: pipeline-name
    value: $(body.sha)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: branch-pipeline
spec:
  params:
  - name: repo-url
  - name: repo-ref
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: $(uid)
    spec:
      pipelineRef:
        name: pipeline
      workspaces:
      - name: all-workspaces
        persistentVolumeClaim:
          claimName: pipeline-all-workspaces-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: pipeline-all-workspaces-pvc
        subPath: $(uid)
      - name: mvn-settings
        configmap:
          name: mvn-settings
      - name: mvn-local-repo
        persistentVolumeClaim:
          claimName: pipeline-mvn-repo-pvc
      params:
      - name: work-id
        value: test1234567
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: repo-ref
        value: $(tt.params.repo-ref)
      - name: src-root
        value: ""
