apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-chat
spec:
  serviceAccountName: trigger
  triggers:
  - name: gitea-chat
    interceptors:
    - cel:
        filter: "body.comment.body.indexOf('/') > -1"
    bindings:
    - ref: parse-gitea-chat
    template:
      name: gitea-chat
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: parse-gitea-chat
spec:
  params:
  - name: issue-id
    value: $(body.issue.id)
  - name: comment
    value: $(body.comment.body)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitea-chat
spec:
  params:
  - name: issue-id
  - name: comment
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: gitea-chat-$(uid)
    spec:
      pipelineRef:
        name: gitea-chat
      params:
      - name: issue-id
        value: $(params.issue-id)
      - name: comment
        value: $(params.comment)
