apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${PURPOSE}-env-alloc
spec:
  params:
  - name: repo-full-name
    description: git仓库名称
  - name: repo-url
    description: git仓库URL
  - name: repo-branch
    description: git仓库分支
  - name: repo-ref
    description: git仓库SHA
  - name: git-server
    description: git server host (如:http://localhost:30280)

  tasks:
  - name: params
    taskSpec:
      steps:
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          echo -n '$(params.repo-url)' | sed 's/.git$/${MANIFEST_SUFFIX}.git/' \
          > $(results.repo-url.path)
          echo -n '$(params.repo-full-name)'${MANIFEST_SUFFIX} > $(results.repo-full-name.path)

          function parse() {
            local value=$1
            # [a-z0-9]([-a-z0-9]*[a-z0-9])?
            echo $value | tr /[A-Z]. -[a-z]- | grep '[^-].*[^-]' -o | xargs echo -n
          }

          parse $(params.repo-full-name) > $(results.repo-full-name-ns.path)
          parse $(params.repo-branch) > $(results.repo-branch-ns.path)
      params:
      - name: repo-url
      - name: repo-full-name
      - name: repo-branch
      results:
      - name: repo-url
      - name: repo-full-name
      - name: repo-full-name-ns
      - name: repo-branch-ns
    params:
    - name: repo-url
      value: $(params.repo-url)
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: repo-branch
      value: $(params.repo-branch)

  - name: flux-init-apply
    taskRef:
      kind: ClusterTask
      name: pipelinerun-apply
    params:
    - name: name
      value: $(context.pipelineRun.name)-${BRANCH_TYPE}flux-init
    - name: spec
      value: |
        pipelineRef:
          name: flux-init
        serviceAccountName: pipeline
        serviceAccountNames:
        - taskName: init-flux-env
          serviceAccountName: init-flux-env
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: pipeline-all-workspaces-pvc
          subPath: $(context.pipelineRun.name)-$(params.repo-ref)
        - name: add
          configmap:
            name: env-manifest
        - name: token
          secret:
            SecretName: gitea-user-token
        params:
        - name: repo-url
          value: $(tasks.params.results.repo-url)
        - name: repo-full-name
          value: $(tasks.params.results.repo-full-name)
        - name: git-server
          value: $(params.git-server)
        - name: paths
          value: |
            $(tasks.params.results.repo-branch-ns)-${ENV}
        - name: namespaces
          value: |
            $(tasks.params.results.repo-full-name-ns)-$(tasks.params.results.repo-branch-ns)-${ENV}
        - name: webhook
          value: ${WEBHOOK}
        - name: cluster-role
          value: pipeline:init-flux-env:$(tasks.params.results.repo-full-name-ns)-flux
