apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trigger
rules:
- apiGroups:
  - ""
  - "triggers.tekton.dev"
  resources:
  - configmaps
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trigger
subjects:
- kind: ServiceAccount
  name: trigger
