apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envsReply
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - list
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envsReply
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envsReply
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: pipeline-git-ssh
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envsReply
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envsReply
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: pipeline-git-ssh
  namespace: default
