apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
  - create
  - list
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: branch-created
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  resourceNames:
  - ${NAMESPACE_PREFIX}*
  verbs:
  - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: branch-created
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: branch-created
subjects:
- kind: ServiceAccount
  name: tekton-triggers-controller
  namespace: ${NAMESPACE}
