apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitea-settings 
spec:
  params:
  - name: repo-full-name
    description: git仓库名称
  - name: webhooks
    description: | 
      webhook配置, 可指定多行, 每行一条配置
      格式: notifyUrl branchFilter events(逗号分隔)
  - name: git-server
    description: git server host (如:http://localhost:30280)

  workspaces:
  - name: token
    description: 存储gitea user token (于/token文件)

  tasks:
  - name: params
    taskSpec:
      steps:
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          while read line; do
            if test -z "$line"; then
              continue
            fi
            echo '$(params.repo-full-name)' $line >> $(results.webhook-args.path)
          done <<EOF
          $(params.webhooks)
          EOF
      params:
      - name: repo-full-name
      - name: webhooks
      results:
      - name: webhook-args
    params:
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: webhooks
      value: $(params.webhooks)

  - name: create-webhook
    taskRef:
      kind: ClusterTask
      name: gitea
    params:
    - name: git-server
      value: $(params.git-server)
    - name: cmd
      value: createWebHook
    - name: args
      value: $(tasks.params.results.webhook-args)
    workspaces:
    - name: token
      workspace: token
