apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
secrets:
- name: git-ssh
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
  - create
  - list
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
