apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ${BRANCH_TYPE}branch-created
spec:
  serviceAccountName: trigger
  triggers:
  - name: branch-created
    bindings:
    - ref: branch-created-params-binding
    template:
      name: ${BRANCH_TYPE}branch-created
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: branch-created-params-binding
spec:
  params:
  - name: repo-full-name
    value: $(body.repository.full_name)
  - name: repo-url
    value: $(body.repository.ssh_url)
  - name: repo-branch
    value: $(body.ref)
  - name: repo-ref
    value: $(body.sha)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ${BRANCH_TYPE}branch-created
spec:
  params:
  - name: repo-full-name
  - name: repo-url
  - name: repo-branch
  - name: repo-ref
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: ${BRANCH_TYPE}branch-created-$(uid)
    spec:
      pipelineRef:
        name: ${BRANCH_TYPE}branch-created
      serviceAccountName: pipeline
      params:
      - name: repo-full-name
        value: $(params.repo-full-name)
      - name: repo-url
        value: $(params.repo-url)
      - name: repo-branch
        value: $(params.repo-branch)
      - name: repo-ref
        value: $(params.repo-ref)
