apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${PURPOSE}-env-factory
spec:
  params:
  - name: repo-full-name
    description: git仓库名称
  - name: repo-url
    description: git仓库URL
  - name: repo-ref
    description: git仓库SHA
  - name: git-server
    description: git server host (如:http://localhost:30280)
    
  - name: env-version
    description: 环境版本

  tasks:
  - name: params
    taskSpec:
      steps:
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          echo -n '$(params.repo-url)' | sed 's/.git$/${MANIFEST_SUFFIX}.git/' \
          > $(results.manifest-repo-url.path)
          echo -n '$(params.repo-full-name)'${MANIFEST_SUFFIX} > $(results.manifest-repo-full-name.path)

          function parse() {
            local value=$1
            # [a-z0-9]([-a-z0-9]*[a-z0-9])?
            echo $value | tr /[A-Z]. -[a-z]- | grep '[^-].*[^-]' -o | xargs echo -n
          }

          parse $(params.repo-full-name) > $(results.manifest-repo-full-name-ns.path)
          parse $(params.env-version) > $(results.env-version-ns.path)
      params:
      - name: repo-url
      - name: repo-full-name
      - name: env-version
      results:
      - name: manifest-repo-url
        description: 资源项目仓库URL
      - name: manifest-repo-full-name
        description: 资源项目仓库名称
      - name: manifest-repo-full-name-ns
        description: 资源项目仓库名称namespace格式
      - name: env-version-ns
    params:
    - name: repo-url
      value: $(params.repo-url)
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: env-version
      value: $(params.env-version)

  - name: flux-init-apply
    taskRef:
      kind: ClusterTask
      name: pipelinerun-apply
    params:
    - name: name
      value: $(context.pipelineRun.name)-flux-init
    - name: spec
      value: |
        pipelineRef:
          name: flux-init
        serviceAccountName: pipeline
        serviceAccountNames:
        - taskName: init-flux-env
          serviceAccountName: init-flux-env
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: pipeline-all-workspaces-pvc
          subPath: $(context.pipelineRun.name)-$(params.repo-ref)
        - name: add
          configmap:
            name: env-manifest
        - name: token
          secret:
            SecretName: gitea-user-token
        params:
        - name: repo-url
          value: $(tasks.params.results.manifest-repo-url)
        - name: repo-full-name
          value: $(tasks.params.results.manifest-repo-full-name)
        - name: git-server
          value: $(params.git-server)
        - name: paths
          value: |
            ${PURPOSE}-$(params.env-version)/${ENV}
        - name: namespaces
          value: |
            $(tasks.params.results.manifest-repo-full-name-ns)-${PURPOSE}-$(tasks.params.results.env-version-ns)-${ENV}
        - name: webhook
          value: ${WEBHOOK}
        - name: cluster-role
          value: pipeline:init-flux-env:$(tasks.params.results.manifest-repo-full-name-ns)-flux
