apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: branch-push-pipeline-wrapper
spec:
  params:
  - name: job-id
    description: 任务ID,串联起所有子流水线

#  - name: promotion-name
#    description: promotion name
#    default: "release"
  - name: env-version
    description: env version, 用于关联具体env
    default: "0.1.1"
    
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-branch
    description: git仓库分支
  - name: repo-ref
    description: git仓库SHA
  - name: repo-url
    description: git仓库URL

  - name: git-server-http
    description: git server host (如:http://localhost:30280)
#  - name: issue-id
#    description: 工单ID, 用以与用户交互


  workspaces:
  - name: project
    description: 存储项目
  - name: gitea-user-token


  tasks:
  - name: get-promotion-name
    taskRef:
      kind: ClusterTask
      name: promotion-config
    params:
    - name: opt
      value: get
    - name: branch
      value: $(params.repo-branch)

  - name: get-issue-id
    taskRef:
      kind: ClusterTask
      name: gitea
    params:
    - name: git-server
      value: $(params.git-server-http)
    - name: cmd
      value: getIssueId
    - name: args
      value: |
        $(params.repo-full-name) $(tasks.get-promotion-name.results.promotion-name)-$(params.env-version)-pipeline
    workspaces:
    - name: token
      workspace: gitea-user-token
      
  - name: fetch-repo
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: project
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-ref)
    - name: deleteExisting
      value: "true"