apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml

patchesStrategicMerge:
- flux-ssh-config-patch.yaml
- fluxcloud-patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: flux
  path: flux-args-patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: flux
  path: flux-role-patch.yaml
 

configMapGenerator:
- name: flux-ssh-config
  files:
  - known_hosts=ssh-config.yaml
generatorOptions:
  disableNameSuffixHash: true

namespace: NAMESPACE_PLACEHOLDER
