apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: branch-push-pipeline-wrapper
spec:
  params:
  - name: job-id
    description: 任务ID,串联起所有子流水线

  - name: env-version
    description: env version, 用于关联具体env
    
  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
  - name: repo-branch
    description: git仓库分支
  - name: repo-ref
    description: git仓库SHA
  - name: repo-url
    description: git仓库URL
  - name: manifest-repo-suffix
    default: "-manifest"
    description: 资源仓库后缀, 追加到git仓库后

  - name: git-server-http
    description: git server host (如:http://localhost:30280)


  workspaces:
  - name: pipelines
    description: |
      由job-id分离各流水线数据目录
      结构: temporary/project-repo
                      manifest-repo
            persistent/
  - name: gitea-user-token


  tasks:
  - name: fetch-repo
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: pipelines
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-ref)
    - name: subdirectory
      value: $(params.job-id)/temporary/project-repo
    - name: deleteExisting
      value: "true"
      
  - name: params
    taskSpec:
      workspaces:
      - name: pipelines
      params:
      - name: repo-url
      - name: repo-full-name
      - name: manifest-repo-suffix
      results:
      - name: pipelines-claim
        description: pipelines-pvc claim
      - name: manifest-repo-url
        description: 资源仓库URL
      - name: manifest-repo-full-name
        description: 资源仓库名称   
      steps:
      - image: 10.1.40.43:5000/busybox:1.31
        script: |
          echo -n $(workspaces.pipelines.claim) > $(results.pipelines-claim.path)
          
          manifestRepoSuffix="$(params.manifest-repo-suffix)"
          echo -n '$(params.repo-url)' | sed "s/.git$/${manifestRepoSuffix}.git/" \
          > $(results.manifest-repo-url.path)
          echo -n '$(params.repo-full-name)'${manifestRepoSuffix} > $(results.manifest-repo-full-name.path)
    workspaces:
    - name: pipelines
      workspace: pipelines
    params:
    - name: repo-url
      value: $(params.repo-url)
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: manifest-repo-suffix
      value: $(params.manifest-repo-suffix)
      
  - name: update-promotion-pipeline
    runAfter:
    - fetch-repo
    taskRef:
      kind: ClusterTask
      name: promotion-config-convert
    params:
    - name: scan-path
      value: $(params.job-id)/temporary/project-repo
    - name: repo-branch
      value: $(params.repo-branch)
    - name: deploy-success-webhook
      value: "xxxxxxxxxxxxx"
    workspaces:
    - name: resources
      workspace: pipelines
      
  - name: get-promotion-name
    runAfter:
    - update-promotion-pipeline
    taskRef:
      kind: ClusterTask
      name: promotion-name
    params:
    - name: branch
      value: $(params.repo-branch)

  - name: init-issue
    taskRef:
      kind: ClusterTask
      name: gitea
    params:
    - name: git-server
      value: $(params.git-server-http)
    - name: cmd
      value: createIssue
    - name: args
      value: |
        $(params.repo-full-name) $(tasks.get-promotion-name.results.output)-$(params.env-version)-pipeline
    - name: idempotent
      value: "true"
    workspaces:
    - name: token
      workspace: gitea-user-token

  - name: trigger
    runAfter:
    - fetch-repo
    taskRef:
      kind: ClusterTask
      name: pipelinerun-apply
    params:
    - name: name
      value: $(context.pipelineRun.name)-trigger-$(tasks.get-promotion-name.results.output)
    - name: spec
      value: |
        pipelineRef:
          name: $(tasks.get-promotion-name.results.output)
        serviceAccountName: pipeline
        workspaces:
        - name: pipeline 
          persistentVolumeClaim:
            claimName: $(tasks.params.results.pipelines-claim)
          subPath: $(params.job-id)
        params:
        - name: job-id
          value: "$(params.job-id)"
        - name: pipelines-claim
          value: "$(tasks.params.results.pipelines-claim)"
        - name: promotion-name
          value: "$(tasks.get-promotion-name.results.output)"
        - name: env-version
          value: "$(params.env-version)"
        - name: repo-full-name
          value: "$(params.repo-full-name)"
        - name: repo-branch
          value: "$(params.repo-branch)"
        - name: repo-ref
          value: "$(params.repo-ref)"
        - name: repo-url
          value: $(params.repo-url)
        - name: manifest-repo-full-name
          value: "$(tasks.params.results.manifest-repo-full-name)"
        - name: manifest-repo-url
          value: $(tasks.params.results.manifest-repo-url)
        - name: git-server-http
          value: $(params.git-server-http)
        - name: issue-id
          value: "$(tasks.init-issue.results.output)"