apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: chat-result
spec:
  params:
  - name: title
    description: issue标题
  - name: content
    description: issue内容
  - name: message
    description: 评论内容

  - name: params
    description: 截取[...]后的message

  tasks:    
  - name: params
    taskSpec:
      steps:
      - image: inner-docker-registry:5000/busybox:1.31
        script: |
          while read name value; do
            if test -n "${name}"; then
              eval ${name}=\"${value}\"
            fi
          done <<EOF
          $(echo -e "$(params.content)")
          EOF
          
          read env pass <<EOF
          $(params.params)
          EOF
          
          echo -n ${promotionName}.${envVersion}.${env}.result.menual-test > $(results.name.path)
                    
          if test "${pass}" == "pass"; then
            pass="true"
          else
            pass="false"
          fi
          echo -n ${pass} > $(results.pass.path)
      params:
      - name: content
      - name: params
      results:
      - name: name
      - name: id
      - name: pass
    params:
    - name: content
      value: $(params.content)
    - name: params
      value: $(params.params)
      
  - name: result
    taskRef:
      kind: ClusterTask
      name: padding-set
    params:
    - name: padding-name
      value: $(tasks.params.results.name)
    - name: pass
      value: $(tasks.params.results.pass)