apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: manual-test
spec:
  params:
  - name: job-id
    description: 任务ID,串联起所有子流水线
  - name: pipelines-claim
    description: pipelines-pvc claim, 用于传递给启动的pipelinerun

  - name: env

  - name: promotion-name
    description: promotion name
  - name: env-version
    description: env version, 用于关联具体env

  - name: repo-full-name
    description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
#  - name: repo-branch
#    description: git仓库分支
  - name: repo-ref
    description: git仓库SHA
#  - name: repo-url
#    description: git仓库URL

  - name: manifest-repo-full-name
    description: 资源仓库名称
  - name: manifest-repo-url
    description: 资源仓库URL

  - name: git-server-http
    description: git server host (如:http://localhost:30280)
  - name: issue-id
    description: 工单ID, 用以与用户交互

  - name: deploy-webhook
    description: 部署成功后通知

  - name: await-count
    default: '1440'
  - name: await-interval
    default: '30'


  workspaces:
  - name: pipeline
  - name: gitea-user-token


  tasks:
  - name: env-init
    taskRef:
      kind: ClusterTask
      name: pipelinerun-apply
    params:
    - name: span-id
      value: "$(params.job-id)"
    - name: name
      value: $(context.pipelineRun.name)-env-init
    - name: spec
      value: |
        pipelineRef:
          name: env-init
        serviceAccountName: pipeline
        serviceAccountNames:
        - taskName: init-flux-env
          serviceAccountName: init-flux-env
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: $(params.pipelines-claim)
          subPath: $(params.job-id)/temporary/manifest-repo
        - name: add
          configmap:
            name: env-manifest
        - name: token
          secret:
            SecretName: gitea-user-token
        params:
        - name: promotion-name
          value: $(params.promotion-name)
        - name: env-version
          value: $(params.env-version)
        - name: env
          value: $(params.env)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: manifest-repo-url
          value: $(params.manifest-repo-url)
        - name: manifest-repo-full-name
          value: $(params.manifest-repo-full-name)
        - name: git-server-http
          value: $(params.git-server-http)
        - name: webhook
          value: $(params.deploy-webhook)

  - name: ask
    runAfter:
    - env-init
    taskRef:
      kind: ClusterTask
      name: gitea
    params:
    - name: git-server
      value: $(params.git-server-http)
    - name: cmd
      value: createComment
    - name: args
      value: |
        $(params.repo-full-name) $(params.issue-id) '是否部署到此环境. yes / no'
    workspaces:
    - name: token
      workspace: gitea-user-token

  - name: await-answer
    runAfter:
    - ask
    conditions:
    - conditionRef: env-selector
      params:
      - name: selector-name
        value: $(params.promotion-name).$(params.env-version).$(params.env).menual-test
      - name: candidate
        value: $(params.job-id)
      - name: await-count
        value: $(params.await-count)
      - name: await-interval
        value: $(params.await-interval)
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo

  - name: tag-deploy-images
    runAfter:
    - await-answer
    conditions:
    - conditionRef: env-lock
      params:
      - name: lock-name
        value: $(params.promotion-name).$(params.env-version).$(params.env).menual-test
      - name: owner-name
        value: $(params.job-id)
      - name: await-count
        value: $(params.await-count)
      - name: await-interval
        value: $(params.await-interval)
    taskSpec:
      steps:
      - image: busybox:1.31
        command:
        - echo
#    taskRef:
#      name: kaniko
#    workspaces:
#    - name: source
#      workspace: workspace
#    params:
#    - name: destination
#     value: 10.1.40.43:5000/busybox:$(params.repo-ref)

  - name: await-deploy-success
    runAfter:
    - tag-deploy-images
    taskRef:
      kind: ClusterTask
      name: padding
    params:
    - name: padding-name
      value: $(params.promotion-name).$(params.env-version).$(params.env).deploy.menual-test
    - name: await-count
      value: $(params.await-count)
    - name: await-interval
      value: $(params.await-interval)

  - name: notify-deploy-success
    runAfter:
    - await-deploy-success
    taskRef:
      kind: ClusterTask
      name: gitea
    params:
    - name: cmd
      value: createComment
    - name: args
      value: |
        $(params.repo-full-name) $(params.issue-id) '已否部署到此环境. 是否可继续. yes / no'
    workspaces:
    - name: token
      workspace: gitea-user-token

  - name: await-manual-result
    runAfter:
    - notify-deploy-success
    taskRef:
      kind: ClusterTask
      name: padding
    params:
    - name: padding-name
      value: $(params.promotion-name).$(params.env-version).$(params.env).result.menual-test
    - name: await-count
      value: $(params.await-count)
    - name: await-interval
      value: $(params.await-interval)

  - name: release-lock
    runAfter:
    - await-manual-result
    taskRef:
      kind: ClusterTask
      name: env-lock-release
    params:
    - name: lock-name
      value: $(params.promotion-name).$(params.env-version).$(params.env).menual-test
    - name: owner-name
      value: $(params.job-id)
