apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-add
spec:
  workspaces:
  - name: workspace
    description: git项目 (含.git目录)
  - name: add
    description: 自定义文件

  params:
  - name: user
    default: none
  - name: email
    default: none@no.user.com

  - name: script-file
    default: script.sh
    description: |
      add workspace内脚本路径, 用以将文件放置于git项目期望位置
      cwd= add workspace根目录
      $1= workspace ~ 根目录
  - name: script-params
    description: |
      将内容作为参数传于script-file
      从$2起
      $1固定为git项目路径

  - name: message
    description: git commit message

  steps:
    - name: add
      image: 10.1.40.43:5000/alpine/git:1.0.17
      workingDir: $(workspaces.workspace.path)
      script: |
        ln -s $HOME/.ssh /root/.ssh

        cd $(workspaces.add.path)
        sh $(workspaces.add.path)/$(params.script-file) $(workspaces.workspace.path) $(params.script-params)
        cd -

        git config --global user.email "$(params.email)"
        git config --global user.name "$(params.user)"

        git add -A .
        git commit -m "$(params.message)"

        git push origin
