apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: gitea
spec:
  workspaces:
  - name: token
    description: 需存在名为token文件, 存储gitea-user-token
    readOnly: true

  params:
    - name: git-server
      description: git server host
      default: "http://gitea-gitea-http:3000"

    - name: cmd
      description: addDeployKey / createIssue / createComment
    - name: args
      description: |
        传于gitea相应请求, 可支持循环
        createUser:  userName password email
        createToken:  userName password tokenName
        createRepo:  owner type(user/org) repoName repoDescription
        addCollaborator:  repoFullName userName permission
        addPublicKey:  title key
        addDeployKey:  repoFullName title key readOnly
        createIssue:  repoFullName title body assignees
        getIssueId:  repoFullName title
        createComment:  repoFullName issueId body
        createWebHook:  repoFullName notifyUrl branchFilter events secret (多个event以逗号分隔)

    - name: idempotent
      default: "false"
      description: 幂等 (现仅作用于createIssue)


  results:
  - name: output
  - name: repo-url
    description: |
      仅createRepo时返回, 格式为: repo-name ssh-url

  volumes:
  - name: output
    emptyDir: {}

  steps:
    - name: jq
      image: inner-docker-registry:5000/stedolan/jq
      volumeMounts:
      - name: output
        mountPath: /volumes/output
      script: |
        cd /volumes/output
        cp /usr/local/bin/jq .

    - name: await
      image: inner-docker-registry:5000/curlimages/curl:7.71.1
      volumeMounts:
      - name: output
        mountPath: /volumes/output
      script: |
        set -ex
        set -o pipefail
        
        export PATH=$PATH:/volumes/output
        
        function createUser() {
          local userName=$1
          local password=$2
          local email=${3:-${userName}@user.noreply.git}
          
          local server=$(params.git-server)
          curl -X POST ${server}/user/sign_up \
          -H "Accept-Language: zh-CN,zh" \
          --data-urlencode "user_name=${userName}" \
          --data-urlencode "email=${email}" \
          --data-urlencode "password=${password}" \
          --data-urlencode "retype=${password}" \
          > .createUser.result
          
          echo $(grep '<p>' .createUser.result)
          return $(cat .createUser.result|wc -l)
        }
        
        function createToken() {
          local userName=$1
          local password=$2
          local tokenName=$3
          
          local auth=$(echo -n ${userName}:${password} | base64 | awk '{printf $0}')
          
          local server=$(params.git-server)
          curl -X POST ${server}/api/v1/users/${userName}/tokens \
          -H "accept: application/json" \
          -H "authorization: Basic ${auth}" \
          -H "Content-Type: application/json" \
          -d "{ \"name\": \"${tokenName}\"}" -f \
          | jq -r .sha1 
        }
        
        function url() {
          method=$1
          path=$2
          server=$(params.git-server)
          token=$(cat $(workspaces.token.path)/token)
          data=$3
         
          if echo $path | grep ? 2>&1 >/dev/null; then
            path="$path&access_token=$token"
          else
            path=$path?access_token=$token
          fi
          
          echo "curl -X $method" \
                \"$server/api/v1$path\" \
                -H \"accept: application/json\" -H \"Content-Type: application/json\" \
                -d \'$data\' \
                -f
        }
        
        function createRepo() {
          local owner=$1
          local type=$2
          local name=$3
          local description=$4
          
          local path
          if test "$type" == "user"; then
            path=/admin/users/${owner}/repos
          else
            path=/orgs/${owner}/repos
          fi
          
          url=$(url POST $path "{
                  \"name\": \"$name\",
                  \"default_branch\": \"master\",
                  \"private\": false,
                  \"auto_init\": true,
                  \"description\": \"$description\" }")
                  
          local content
          content=$(sh -c "$url")
          
          echo $name $(echo $content | jq -r .ssh_url) >> $(results.repo-url.path)
          echo $content | jq -r .id
        }
        
        function addCollaborator() {
          repoFullName=$1
          name=$2
          permission=${3-write}
          url=$(url PUT /repos/$repoFullName/collaborators/$name "{
                  \"permission\": \"$permission\" }")
          sh -c "$url" | jq -r .id
        }
        
        function addPublicKey() {
          title=$1
          key=$2
          url=$(url POST /user/keys "{
                  \"title\": \"$title\",
                  \"key\": \"$key\" }")
          sh -c "$url" | jq -r .id
        }
        
        function createIssue() {
          repoFullName=$1
          title=$2
          body=$3
          assignees=$4  #(echo $3|sed 's|"|\\"|g')
          
          if test "$(params.idempotent)" == "true"; then
            if getIssueId "$repoFullName" "$title"; then
              return
            fi
          fi
          url=$(url POST /repos/$repoFullName/issues "{
                  \"title\": \"$title\",
                  \"body\": \"$body\", 
                  \"assignees\": [ $assignees ] }")
          sh -c "$url" | jq -r .number
        }
        
        function getIssueId() {
          repoFullName=$1
          title=$2
          url=$(url GET /repos/$repoFullName/issues?type=issues\&q=$title)
          res=$(sh -c "$url")
          
          if test $(echo $res | jq length) -eq 1; then
            res=$(echo $res | jq -r .[0])
            if test $(echo $res | jq -r .title) == $title; then
              echo $res | jq -r .number
              return
            fi
          fi
          return 1
        }
        
        function createComment() {
          repoFullName=$1
          issue=$2
          body=${3//\"/\\\"}
          url=$(url POST /repos/$repoFullName/issues/$issue/comments "{ \"body\": \"$body\" }")
          sh -c "$url" | jq -r .id
        }
        
        function addDeployKey() {
          repoFullName=$1
          title=$2
          key=$3
          readOnly=${4:-false}
          url=$(url POST /repos/$repoFullName/keys "{ \"title\": \"$title\", \"key\": \"$key\", \"read_only\": $readOnly }")
          sh -c "$url" | jq -r .id
        }
        
        function createWebHook() {
          repoFullName=$1
          notifyUrl=$2
          branchFilter=$3
          events=$(echo $4 | sed -e 's/,/\",\"/g' -e 's/^/\"/' -e 's/$/\"/')
          secret=$5
          url=$(url POST /repos/$repoFullName/hooks "{
                  \"type\": \"gitea\",
                  \"branch_filter\": \"$branchFilter\",
                  \"events\": [ $events ],
                  \"config\": {
                    \"url\": \"$notifyUrl\",
                    \"content_type\": \"json\",
                    \"secret\": \"$secret\"
                  },
                  \"active\": true }")
          sh -c "$url" | jq -r .id
        }
        
        while read args; do
          if test -n "$args"; then
            eval $(params.cmd) $args | xargs -I {} echo -n {}" " >> $(results.output.path) 
          else
            true
          fi
        done <<EOF
        $(params.args)
        EOF
        sed -i -r 's/ +$//' $(results.output.path) 
