apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ns-opt
spec:
  params:
    - name: url
      default: https://kubernetes.default

    - name: names
    - name: opt
      description: create / delete / has
      default: create

  results:
  - name: has
    description: "存储has结果. 格式: name bool"
  
  steps:
    - name: await
      image: inner-docker-registry:5000/lachlanevenson/k8s-kubectl
      imagePullPolicy: IfNotPresent 
      script: |
        url=$(params.url)
        ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

        kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"


        names='$(params.names)'

        for name in $names; do
          case "$(params.opt)" in
            has ) 
              has=false
              if $kubectl get ns $name -o jsonpath={.metadata.name}; then
                has=true
              fi
              echo $name $has >> $(results.has.path)
              ;;
            create ) $kubectl create ns $name ;;
            delete ) $kubectl delete ns $name ;;
          esac
        done