apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > auto-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__M3qhix__(params.job-id)"
      - name: name
        value: __M3qhix__(context.pipelineRun.name)-trigger-__M3qhix__{INNER_PIPELINE_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: __M3qhix__{INNER_PIPELINE_NAME}
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __M3qhix__(params.pipelines-claim)
            subPath: __M3qhix__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__M3qhix__(params.job-id)"
          - name: pipelines-claim
            value: "__M3qhix__(params.pipelines-claim)"
          - name: env
            value: "__M3qhix__{ENV}"
          - name: promotion-name
            value: "__M3qhix__(params.promotion-name)"
          - name: env-version
            value: "__M3qhix__(params.env-version)"
          - name: repo-full-name
            value: "__M3qhix__(params.repo-full-name)"
          - name: repo-ref
            value: "__M3qhix__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__M3qhix__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __M3qhix__(params.manifest-repo-url)
          - name: git-server-http
            value: __M3qhix__(params.git-server-http)
          - name: issue-id
            value: "__M3qhix__(params.issue-id)"
          - name: deploy-webhook
            value: "__M3qhix__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__M3qhix__/s/__M3qhix__/$/g' auto-test-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__Adsuoj__(params.job-id)"
      - name: generate-name
        value: manual-test-__Adsuoj__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __Adsuoj__(params.pipelines-claim)
            subPath: __Adsuoj__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__Adsuoj__(params.job-id)"
          - name: pipelines-claim
            value: "__Adsuoj__(params.pipelines-claim)"
          - name: env
            value: "__Adsuoj__{ENV}"
          - name: promotion-name
            value: "__Adsuoj__(params.promotion-name)"
          - name: env-version
            value: "__Adsuoj__(params.env-version)"
          - name: repo-full-name
            value: "__Adsuoj__(params.repo-full-name)"
          - name: repo-ref
            value: "__Adsuoj__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__Adsuoj__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __Adsuoj__(params.manifest-repo-url)
          - name: git-server-http
            value: __Adsuoj__(params.git-server-http)
          - name: issue-id
            value: "__Adsuoj__(params.issue-id)"
          - name: deploy-webhook
            value: "__Adsuoj__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__Adsuoj__/s/__Adsuoj__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __vTVHo1__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __vTVHo1__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__vTVHo1__/s/__vTVHo1__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      AUTO_TEST_TASK_TEMPLATE="auto-test-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__NDuStf__1  #存储项目中资源配置
      shift
      
      pipelineDir=__NDuStf__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__NDuStf__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__NDuStf__1
        if egrep "^ +taskSpec:" __NDuStf__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__NDuStf__1
        
        local pipelineName=__NDuStf__(basename __NDuStf__configFile) \\
           && pipelineName=__NDuStf__{configFile#*pipeline.} \\
           && pipelineName=__NDuStf__{pipelineName%.yaml*}
        
        local branchPattern=__NDuStf__(sed -nr '/^branchPattern: .+__NDuStf__/ {s/^branchPattern: (.+)__NDuStf__/\\1/p;q}' __NDuStf__{configFile})
        if test -z "__NDuStf__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__NDuStf__{PROMOTION_NAME}/__NDuStf__{pipelineName}/" \\
            -e "s/\\__NDuStf__{BRANCH_PATTERN}/__NDuStf__{branchPattern}/" \\
            __NDuStf__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __NDuStf__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __NDuStf__{output}
        
        local configFile=__NDuStf__1
        
        local TEMP_PREFIX="__NDuStf__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __NDuStf__{configFile} __NDuStf__{TEMP_PREFIX}
        
        local file=""
        for file in __NDuStf__{TEMP_PREFIX}*; do
          local task=__NDuStf__(getTaskType __NDuStf__file)
          case __NDuStf__task in
            auto-test ) autoTestTask __NDuStf__file;;
            manual-test ) manualTestTask __NDuStf__file;;
            * ) commonTask __NDuStf__file;;
          esac
        done
        
        rm __NDuStf__{TEMP_PREFIX}* -f
      }
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__NDuStf__1
        local tempPreifx=__NDuStf__2
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__NDuStf__line"|grep ^- 2>&1 >/dev/null; then
            i=__NDuStf__(( __NDuStf__i + 1 ))
            file=__NDuStf__{tempPreifx}__NDuStf__i
            touch __NDuStf__file
          fi
          echo "__NDuStf__line" >> __NDuStf__{file}
        done <<EOF
      __NDuStf__(sed -nr '/^tasks:/,/^[a-zA-Z0-9]/ {/^[- ]/p}' __NDuStf__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__NDuStf__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __NDuStf__{taskFile}
      }
      function getContent() {
        local file=__NDuStf__1
        local key=__NDuStf__2
        
        local hasKey=__NDuStf__3
        local args=
        if test "__NDuStf__hasKey" == "true"; then
          args="/^  __NDuStf__key:/{p;d} /^- __NDuStf__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __NDuStf__key:/,/^  [a-zA-Z0-9]/{__NDuStf__args /^  [- ]/p}" __NDuStf__file
      }
      function getValue() {
        local file=__NDuStf__1
        local name=__NDuStf__2
        local prefix="__NDuStf__3"
        sed -nr "/^__NDuStf__{prefix}- name: __NDuStf__{name}/,/^__NDuStf__{prefix}[^ ]/ {
          /^__NDuStf__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__NDuStf__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__NDuStf__{prefix}    / {
            s/^__NDuStf__{prefix}  (.*)/\\1/p;
          }
        }" __NDuStf__{file}
      }
      
      function commonTask() {
        local taskFile=__NDuStf__1
        if getContent __NDuStf__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __NDuStf__{taskFile} \\
        | awk '{print "  "__NDuStf__0}' >> __NDuStf__{output}
      }
      
      function autoTestTask() {
        local taskFile=__NDuStf__1
        
        local name=__NDuStf__(getContent __NDuStf__{taskFile} name true)
        local innerPipelineName=__NDuStf__{name#*: }
        
        echo "__NDuStf__{name}" | sed -r 's/^ (.*)/  -\\1/' >> __NDuStf__{output}
        getContent __NDuStf__{taskFile} runAfter true | awk '{print "  "__NDuStf__0}' >> __NDuStf__{output}
        
        sed "s/\\__NDuStf__{INNER_PIPELINE_NAME}/__NDuStf__{innerPipelineName}/" __NDuStf__{AUTO_TEST_TASK_TEMPLATE} \\
        | awk '{print "    "__NDuStf__0}' >> __NDuStf__{output}
        getContent __NDuStf__{taskFile} pipelineRun | awk '{print "      "__NDuStf__0}'>> __NDuStf__{output}
      
        
        local innerPipelinePath=__NDuStf__{pipelineDir}/__NDuStf__{innerPipelineName}.yaml
        echo 'apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: '__NDuStf__{innerPipelineName}'
      spec:' >> __NDuStf__{innerPipelinePath}
        getContent __NDuStf__{taskFile} pipelineSpec \\
        | sed -r 's/^  (.*)/\\1/' >> __NDuStf__{innerPipelinePath}
      }
      
      function manualTestTask() {
        local taskFile=__NDuStf__1
        
        local name=__NDuStf__(getContent __NDuStf__{taskFile} name true)
        local innerPipelineRunName=__NDuStf__{name#*: }
        
        echo "__NDuStf__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __NDuStf__{output}
        getContent __NDuStf__{taskFile} runAfter true | awk '{print "  "__NDuStf__0}' >> __NDuStf__{output}
        
        local env=__NDuStf__(getValue __NDuStf__{taskFile} env "  ")
        sed -e "s/\\__NDuStf__{INNER_PIPELINE_RUN_NAME}/__NDuStf__{innerPipelineRunName}/" \\
            -e "s/\\__NDuStf__{ENV}/__NDuStf__{env}/" \\
            -e "s/\\__NDuStf__{DEPLOY_SUCCESS_WEBHOOK}/__NDuStf__{deploySuccessWebhook}/" \\
            __NDuStf__{MANUAL_TEST_TASK_TEMPLATE} \\
        | awk '{print "    "__NDuStf__0}' >> __NDuStf__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __NDuStf__{pipelineDir} -p
      
      for file in __NDuStf__(find __NDuStf__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__NDuStf__{pipelineDir}/__NDuStf__(basename __NDuStf__file)
        
        validateConfig __NDuStf__file
      
        pipelineHeader __NDuStf__file
      
        pipelineTasks __NDuStf__file
      done
      EOFEOFEOFEOF
      sed -i '/__NDuStf__/s/__NDuStf__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
