apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__GRSFux__(params.job-id)"
      - name: generate-name
        value: env-deploy-__GRSFux__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __GRSFux__(params.pipelines-claim)
            subPath: __GRSFux__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__GRSFux__(params.job-id)"
          - name: pipelines-claim
            value: "__GRSFux__(params.pipelines-claim)"
          - name: env
            value: "__GRSFux__{ENV}"
          - name: promotion-name
            value: "__GRSFux__(params.promotion-name)"
          - name: env-version
            value: "__GRSFux__(params.env-version)"
          - name: repo-full-name
            value: "__GRSFux__(params.repo-full-name)"
          - name: repo-ref
            value: "__GRSFux__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__GRSFux__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __GRSFux__(params.manifest-repo-url)
          - name: git-server-http
            value: __GRSFux__(params.git-server-http)
          - name: issue-id
            value: "__GRSFux__(params.issue-id)"
          - name: deploy-webhook
            value: "__GRSFux__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__GRSFux__/s/__GRSFux__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__WLI71j__(params.job-id)"
      - name: generate-name
        value: manual-test-__WLI71j__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __WLI71j__(params.pipelines-claim)
            subPath: __WLI71j__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__WLI71j__(params.job-id)"
          - name: pipelines-claim
            value: "__WLI71j__(params.pipelines-claim)"
          - name: env
            value: "__WLI71j__{ENV}"
          - name: promotion-name
            value: "__WLI71j__(params.promotion-name)"
          - name: env-version
            value: "__WLI71j__(params.env-version)"
          - name: repo-full-name
            value: "__WLI71j__(params.repo-full-name)"
          - name: repo-ref
            value: "__WLI71j__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__WLI71j__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __WLI71j__(params.manifest-repo-url)
          - name: git-server-http
            value: __WLI71j__(params.git-server-http)
          - name: issue-id
            value: "__WLI71j__(params.issue-id)"
          - name: deploy-webhook
            value: "__WLI71j__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__WLI71j__/s/__WLI71j__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __tFoYF2__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __tFoYF2__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__tFoYF2__/s/__tFoYF2__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__LhEEiV__1  #存储项目中资源配置
      shift
      
      pipelineDir=__LhEEiV__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__LhEEiV__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__LhEEiV__1
        if egrep "^ +taskSpec:" __LhEEiV__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__LhEEiV__1
        
        local pipelineName=__LhEEiV__(basename __LhEEiV__configFile) \\
           && pipelineName=__LhEEiV__{configFile#*pipeline.} \\
           && pipelineName=__LhEEiV__{pipelineName%.yaml*}
        
        local branchPattern=__LhEEiV__(sed -nr '/^branchPattern: .+__LhEEiV__/ {s/^branchPattern: (.+)__LhEEiV__/\\1/p;q}' __LhEEiV__{configFile})
        if test -z "__LhEEiV__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__LhEEiV__{PROMOTION_NAME}/__LhEEiV__{pipelineName}/" \\
            -e "s/\\__LhEEiV__{BRANCH_PATTERN}/__LhEEiV__{branchPattern}/" \\
            __LhEEiV__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __LhEEiV__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __LhEEiV__{output}
        
        local configFile=__LhEEiV__1
        
        local TEMP_PREFIX="__LhEEiV__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __LhEEiV__{configFile} __LhEEiV__{TEMP_PREFIX}
        
        local file=""
        for file in __LhEEiV__{TEMP_PREFIX}*; do
          local task=__LhEEiV__(getTaskType __LhEEiV__file)
          case __LhEEiV__task in
            env-deploy ) envDeployTask __LhEEiV__file;;
            manual-test ) manualTestTask __LhEEiV__file;;
            env-lock-release ) envLockReleaseTask __LhEEiV__file;;
            * ) commonTask __LhEEiV__file;;
          esac
        done
        
        rm __LhEEiV__{TEMP_PREFIX}* -f
      }
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__LhEEiV__1
        local tempPreifx=__LhEEiV__2
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__LhEEiV__line"|grep ^- 2>&1 >/dev/null; then
            i=__LhEEiV__(( __LhEEiV__i + 1 ))
            file=__LhEEiV__{tempPreifx}__LhEEiV__i
            touch __LhEEiV__file
          fi
          echo "__LhEEiV__line" >> __LhEEiV__{file}
        done <<EOF
      __LhEEiV__(sed -nr '/^tasks:/,/^[a-zA-Z0-9]/ {/^[- ]/p}' __LhEEiV__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__LhEEiV__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __LhEEiV__{taskFile}
      }
      function getContent() {
        local file=__LhEEiV__1
        local key=__LhEEiV__2
        
        local hasKey=__LhEEiV__3
        local args=
        if test "__LhEEiV__hasKey" == "true"; then
          args="/^  __LhEEiV__key:/{p;d} /^- __LhEEiV__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __LhEEiV__key:/,/^  [a-zA-Z0-9]/{__LhEEiV__args /^  [- ]/p}" __LhEEiV__file
      }
      function getValue() {
        local file=__LhEEiV__1
        local name=__LhEEiV__2
        local prefix="__LhEEiV__3"
        sed -nr "/^__LhEEiV__{prefix}- name: __LhEEiV__{name}/,/^__LhEEiV__{prefix}[^ ]/ {
          /^__LhEEiV__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__LhEEiV__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__LhEEiV__{prefix}    / {
            s/^__LhEEiV__{prefix}  (.*)/\\1/p;
          }
        }" __LhEEiV__{file}
      }
      function addValue() {
        local taskFile=__LhEEiV__1
        local prefix=__LhEEiV__2
        local name=__LhEEiV__3
        local value=__LhEEiV__4
        sed -i "/^__LhEEiV__{prefix}params:/a\\\\__LhEEiV__{prefix}- name: __LhEEiV__{name}\\n__LhEEiV__{prefix}  value: __LhEEiV__{value}" __LhEEiV__{taskFile}
      }
      
      function envLockReleaseTask() {
        local taskFile=__LhEEiV__1
        addValue __LhEEiV__{taskFile} "  " owner-name '"__LhEEiV__(params.job-id)"'
        commonTask __LhEEiV__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__LhEEiV__1
        if getContent __LhEEiV__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __LhEEiV__{taskFile} \\
        | awk '{print "  "__LhEEiV__0}' >> __LhEEiV__{output}
      }
      
      function envDeployTask() {
        deployedTestTask __LhEEiV__1 __LhEEiV__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __LhEEiV__1 __LhEEiV__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__LhEEiV__1
        local templateFile=__LhEEiV__2
        
        local name=__LhEEiV__(getContent __LhEEiV__{taskFile} name true)
        local innerPipelineRunName=__LhEEiV__{name#*: }
        
        echo "__LhEEiV__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __LhEEiV__{output}
        getContent __LhEEiV__{taskFile} runAfter true | awk '{print "  "__LhEEiV__0}' >> __LhEEiV__{output}
        
        local env=__LhEEiV__(getValue __LhEEiV__{taskFile} env "  ")
        sed -e "s/\\__LhEEiV__{INNER_PIPELINE_RUN_NAME}/__LhEEiV__{innerPipelineRunName}/" \\
            -e "s/\\__LhEEiV__{ENV}/__LhEEiV__{env}/" \\
            -e "s/\\__LhEEiV__{DEPLOY_SUCCESS_WEBHOOK}/__LhEEiV__{deploySuccessWebhook}/" \\
            __LhEEiV__{templateFile} \\
        | awk '{print "    "__LhEEiV__0}' >> __LhEEiV__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __LhEEiV__{pipelineDir} -p
      
      for file in __LhEEiV__(find __LhEEiV__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__LhEEiV__{pipelineDir}/__LhEEiV__(basename __LhEEiV__file)
        
        validateConfig __LhEEiV__file
      
        pipelineHeader __LhEEiV__file
      
        pipelineTasks __LhEEiV__file
      done
      EOFEOFEOFEOF
      sed -i '/__LhEEiV__/s/__LhEEiV__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
