apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  - name: namespace
    description: 部署promotion-pipeline到指定命名空间, 默认为当前ns
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      pipelinerunNs="$(params.namespace)"
      if test -n "$pipelinerunNs"; then
        namespace=$pipelinerunNs
      fi

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__IKwjat__(params.job-id)"
      - name: generate-name
        value: env-deploy-__IKwjat__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __IKwjat__(params.pipelines-claim)
            subPath: __IKwjat__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__IKwjat__(params.job-id)"
          - name: pipelines-claim
            value: "__IKwjat__(params.pipelines-claim)"
          - name: env
            value: "__IKwjat__{ENV}"
          - name: promotion-name
            value: "__IKwjat__(params.promotion-name)"
          - name: env-version
            value: "__IKwjat__(params.env-version)"
          - name: repo-full-name
            value: "__IKwjat__(params.repo-full-name)"
          - name: repo-ref
            value: "__IKwjat__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__IKwjat__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __IKwjat__(params.manifest-repo-url)
          - name: git-server-http
            value: __IKwjat__(params.git-server-http)
          - name: issue-id
            value: "__IKwjat__(params.issue-id)"
          - name: deploy-webhook
            value: "__IKwjat__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__IKwjat__/s/__IKwjat__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__k5ryME__(params.job-id)"
      - name: env
        value: __k5ryME__{ENV}
      - name: promotion-name
        value: "__k5ryME__(params.promotion-name)"
      - name: env-version
        value: "__k5ryME__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__k5ryME__/s/__k5ryME__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__16LASz__(params.job-id)"
      - name: generate-name
        value: manual-test-__16LASz__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __16LASz__(params.pipelines-claim)
            subPath: __16LASz__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__16LASz__(params.job-id)"
          - name: pipelines-claim
            value: "__16LASz__(params.pipelines-claim)"
          - name: env
            value: "__16LASz__{ENV}"
          - name: promotion-name
            value: "__16LASz__(params.promotion-name)"
          - name: env-version
            value: "__16LASz__(params.env-version)"
          - name: repo-full-name
            value: "__16LASz__(params.repo-full-name)"
          - name: repo-ref
            value: "__16LASz__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__16LASz__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __16LASz__(params.manifest-repo-url)
          - name: git-server-http
            value: __16LASz__(params.git-server-http)
          - name: issue-id
            value: "__16LASz__(params.issue-id)"
          - name: deploy-webhook
            value: "__16LASz__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__16LASz__/s/__16LASz__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __6KwjNL__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __6KwjNL__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__6KwjNL__/s/__6KwjNL__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__rwsysy__1  #存储项目中资源配置
      shift
      
      pipelineDir=__rwsysy__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__rwsysy__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__rwsysy__1
        if egrep "^ +taskSpec:" __rwsysy__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__rwsysy__1
        
        local pipelineName=__rwsysy__(basename __rwsysy__configFile) \\
           && pipelineName=__rwsysy__{configFile#*pipeline.} \\
           && pipelineName=__rwsysy__{pipelineName%.yaml*}
        
        local branchPattern=__rwsysy__(sed -nr '/^branchPattern: .+__rwsysy__/ {s/^branchPattern: (.+)__rwsysy__/\\1/p;q}' __rwsysy__{configFile})
        if test -z "__rwsysy__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__rwsysy__{PROMOTION_NAME}/__rwsysy__{pipelineName}/" \\
            -e "s/\\__rwsysy__{BRANCH_PATTERN}/__rwsysy__{branchPattern}/" \\
            __rwsysy__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __rwsysy__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __rwsysy__{output}
        
        local configFile=__rwsysy__1
        
        local TEMP_PREFIX="__rwsysy__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __rwsysy__{configFile} __rwsysy__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __rwsysy__{TEMP_PREFIX}*; do
          local task=__rwsysy__(getTaskType __rwsysy__file)
          case __rwsysy__task in
            env-deploy ) envDeployTask __rwsysy__file;;
            manual-test ) manualTestTask __rwsysy__file;;
            env-release ) envReleaseTask __rwsysy__file;;
            * ) commonTask __rwsysy__file;;
          esac
        done
        
        rm __rwsysy__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__rwsysy__1
        
        if grep "^finally:" 2>&1 >/dev/null __rwsysy__{configFile}; then
          echo "  finally:" >> __rwsysy__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__rwsysy__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __rwsysy__{configFile} __rwsysy__{TEMP_PREFIX} finally
        
        local file=""
        for file in __rwsysy__{TEMP_PREFIX}*; do
          local task=__rwsysy__(getTaskType __rwsysy__file)
          case __rwsysy__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __rwsysy__file;;
            * ) commonTask __rwsysy__file;;
          esac
        done
        
        rm __rwsysy__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__rwsysy__1
        local tempPreifx=__rwsysy__2
        local section=__rwsysy__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__rwsysy__line"|grep ^- 2>&1 >/dev/null; then
            i=__rwsysy__(( __rwsysy__i + 1 ))
            file=__rwsysy__{tempPreifx}__rwsysy__i
            touch __rwsysy__file
          fi
          echo "__rwsysy__line" >> __rwsysy__{file}
        done <<EOF
      __rwsysy__(sed -nr "/^__rwsysy__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __rwsysy__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__rwsysy__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __rwsysy__{taskFile}
      }
      function getContent() {
        local file=__rwsysy__1
        local key=__rwsysy__2
        
        local hasKey=__rwsysy__3
        local args=
        if test "__rwsysy__hasKey" == "true"; then
          args="/^  __rwsysy__key:/{p;d} /^- __rwsysy__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __rwsysy__key:/,/^  [a-zA-Z0-9]/{__rwsysy__args /^  [- ]/p}" __rwsysy__file
      }
      function getValue() {
        local file=__rwsysy__1
        local name=__rwsysy__2
        local prefix="__rwsysy__3"
        sed -nr "/^__rwsysy__{prefix}- name: __rwsysy__{name}/,/^__rwsysy__{prefix}[^ ]/ {
          /^__rwsysy__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__rwsysy__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__rwsysy__{prefix}    / {
            s/^__rwsysy__{prefix}  (.*)/\\1/p;
          }
        }" __rwsysy__{file}
      }
      function addValue() {
        local taskFile=__rwsysy__1
        local prefix=__rwsysy__2
        local name=__rwsysy__3
        local value=__rwsysy__4
        sed -i "/^__rwsysy__{prefix}params:/a\\\\__rwsysy__{prefix}- name: __rwsysy__{name}\\n__rwsysy__{prefix}  value: __rwsysy__{value}" __rwsysy__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__rwsysy__1
        if getContent __rwsysy__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __rwsysy__{taskFile} \\
        | awk '{print "  "__rwsysy__0}' >> __rwsysy__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __rwsysy__1 __rwsysy__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __rwsysy__1 __rwsysy__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __rwsysy__1 __rwsysy__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__rwsysy__1
        local templateFile=__rwsysy__2
        
        local name=__rwsysy__(getContent __rwsysy__{taskFile} name true)
        local innerPipelineRunName=__rwsysy__{name#*: }
        
        echo "__rwsysy__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __rwsysy__{output}
        getContent __rwsysy__{taskFile} runAfter true | awk '{print "  "__rwsysy__0}' >> __rwsysy__{output}
        
        local env=__rwsysy__(getValue __rwsysy__{taskFile} env "  ")
        sed -e "s/\\__rwsysy__{INNER_PIPELINE_RUN_NAME}/__rwsysy__{innerPipelineRunName}/" \\
            -e "s/\\__rwsysy__{ENV}/__rwsysy__{env}/" \\
            -e "s/\\__rwsysy__{DEPLOY_SUCCESS_WEBHOOK}/__rwsysy__{deploySuccessWebhook}/" \\
            __rwsysy__{templateFile} \\
        | awk '{print "    "__rwsysy__0}' >> __rwsysy__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __rwsysy__{pipelineDir} -p
      
      for file in __rwsysy__(find __rwsysy__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__rwsysy__{pipelineDir}/__rwsysy__(basename __rwsysy__file)
        
        validateConfig __rwsysy__file
      
        pipelineHeader __rwsysy__file
      
        pipelineTasks __rwsysy__file
        
        pipelineFinally __rwsysy__file
      done
      EOFEOFEOFEOF
      sed -i '/__rwsysy__/s/__rwsysy__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
