apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > auto-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: name
        value: __CdW1fo__(context.pipelineRun.name)-trigger-__CdW1fo__{INNER_PIPELINE_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: __CdW1fo__{INNER_PIPELINE_NAME}
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __CdW1fo__(params.pipelines-claim)
            subPath: __CdW1fo__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__CdW1fo__(params.job-id)"
          - name: pipelines-claim
            value: "__CdW1fo__(params.pipelines-claim)"
          - name: env
            value: "__CdW1fo__{ENV}"
          - name: promotion-name
            value: "__CdW1fo__(params.promotion-name)"
          - name: env-version
            value: "__CdW1fo__(params.env-version)"
          - name: repo-full-name
            value: "__CdW1fo__(params.repo-full-name)"
          - name: repo-ref
            value: "__CdW1fo__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__CdW1fo__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __CdW1fo__(params.manifest-repo-url)
          - name: git-server-http
            value: __CdW1fo__(params.git-server-http)
          - name: issue-id
            value: "__CdW1fo__(params.issue-id)"
          - name: deploy-webhook
            value: "__CdW1fo__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__CdW1fo__/s/__CdW1fo__/$/g' auto-test-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: name
        value: __oIVx6o__(context.pipelineRun.name)-trigger-manual-test-__oIVx6o__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __oIVx6o__(params.pipelines-claim)
            subPath: __oIVx6o__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__oIVx6o__(params.job-id)"
          - name: pipelines-claim
            value: "__oIVx6o__(params.pipelines-claim)"
          - name: env
            value: "__oIVx6o__{ENV}"
          - name: promotion-name
            value: "__oIVx6o__(params.promotion-name)"
          - name: env-version
            value: "__oIVx6o__(params.env-version)"
          - name: repo-full-name
            value: "__oIVx6o__(params.repo-full-name)"
          - name: repo-ref
            value: "__oIVx6o__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__oIVx6o__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __oIVx6o__(params.manifest-repo-url)
          - name: git-server-http
            value: __oIVx6o__(params.git-server-http)
          - name: issue-id
            value: "__oIVx6o__(params.issue-id)"
          - name: deploy-webhook
            value: "__oIVx6o__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__oIVx6o__/s/__oIVx6o__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __dwlQ3U__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __dwlQ3U__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__dwlQ3U__/s/__dwlQ3U__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      AUTO_TEST_TASK_TEMPLATE="auto-test-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__RicbmK__1  #存储项目中资源配置
      shift
      
      pipelineDir=__RicbmK__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__RicbmK__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__RicbmK__1
        if egrep "^ +taskSpec:" __RicbmK__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__RicbmK__1
        
        local pipelineName=__RicbmK__(basename __RicbmK__configFile) \\
           && pipelineName=__RicbmK__{configFile#*pipeline.} \\
           && pipelineName=__RicbmK__{pipelineName%.yaml*}
        
        local branchPattern=__RicbmK__(sed -nr '/^branchPattern: .+__RicbmK__/ {s/^branchPattern: (.+)__RicbmK__/\\1/p;q}' __RicbmK__{configFile})
        if test -z "__RicbmK__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__RicbmK__{PROMOTION_NAME}/__RicbmK__{pipelineName}/" \\
            -e "s/\\__RicbmK__{BRANCH_PATTERN}/__RicbmK__{branchPattern}/" \\
            __RicbmK__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __RicbmK__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __RicbmK__{output}
        
        local configFile=__RicbmK__1
        
        local TEMP_PREFIX="__RicbmK__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __RicbmK__{configFile} __RicbmK__{TEMP_PREFIX}
        
        local file=""
        for file in __RicbmK__{TEMP_PREFIX}*; do
          local task=__RicbmK__(getTaskType __RicbmK__file)
          case __RicbmK__task in
            auto-test ) autoTestTask __RicbmK__file;;
            manual-test ) manualTestTask __RicbmK__file;;
            * ) commonTask __RicbmK__file;;
          esac
        done
        
        rm __RicbmK__{TEMP_PREFIX}* -f
      }
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__RicbmK__1
        local tempPreifx=__RicbmK__2
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__RicbmK__line"|grep ^- 2>&1 >/dev/null; then
            i=__RicbmK__(( __RicbmK__i + 1 ))
            file=__RicbmK__{tempPreifx}__RicbmK__i
            touch __RicbmK__file
          fi
          echo "__RicbmK__line" >> __RicbmK__{file}
        done <<EOF
      __RicbmK__(sed -nr '/^tasks:/,/^[a-zA-Z0-9]/ {/^[- ]/p}' __RicbmK__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__RicbmK__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __RicbmK__{taskFile}
      }
      function getContent() {
        local file=__RicbmK__1
        local key=__RicbmK__2
        
        local hasKey=__RicbmK__3
        local args=
        if test "__RicbmK__hasKey" == "true"; then
          args="/^  __RicbmK__key:/{p;d} /^- __RicbmK__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __RicbmK__key:/,/^  [a-zA-Z0-9]/{__RicbmK__args /^  [- ]/p}" __RicbmK__file
      }
      function getValue() {
        local file=__RicbmK__1
        local name=__RicbmK__2
        local prefix="__RicbmK__3"
        sed -nr "/^__RicbmK__{prefix}- name: __RicbmK__{name}/,/^__RicbmK__{prefix}[^ ]/ {
          /^__RicbmK__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__RicbmK__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__RicbmK__{prefix}    / {
            s/^__RicbmK__{prefix}  (.*)/\\1/p;
          }
        }" __RicbmK__{file}
      }
      
      function commonTask() {
        local taskFile=__RicbmK__1
        if getContent __RicbmK__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __RicbmK__{taskFile} \\
        | awk '{print "  "__RicbmK__0}' >> __RicbmK__{output}
      }
      
      function autoTestTask() {
        local taskFile=__RicbmK__1
        
        local name=__RicbmK__(getContent __RicbmK__{taskFile} name true)
        local innerPipelineName=__RicbmK__{name#*: }
        
        echo "__RicbmK__{name}" | sed -r 's/^ (.*)/  -\\1/' >> __RicbmK__{output}
        getContent __RicbmK__{taskFile} runAfter true | awk '{print "  "__RicbmK__0}' >> __RicbmK__{output}
        
        sed "s/\\__RicbmK__{INNER_PIPELINE_NAME}/__RicbmK__{innerPipelineName}/" __RicbmK__{AUTO_TEST_TASK_TEMPLATE} \\
        | awk '{print "    "__RicbmK__0}' >> __RicbmK__{output}
        getContent __RicbmK__{taskFile} pipelineRun | awk '{print "      "__RicbmK__0}'>> __RicbmK__{output}
      
        
        local innerPipelinePath=__RicbmK__{pipelineDir}/__RicbmK__{innerPipelineName}.yaml
        echo 'apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: '__RicbmK__{innerPipelineName}'
      spec:' >> __RicbmK__{innerPipelinePath}
        getContent __RicbmK__{taskFile} pipelineSpec \\
        | sed -r 's/^  (.*)/\\1/' >> __RicbmK__{innerPipelinePath}
      }
      
      function manualTestTask() {
        local taskFile=__RicbmK__1
        
        local name=__RicbmK__(getContent __RicbmK__{taskFile} name true)
        local innerPipelineRunName=__RicbmK__{name#*: }
        
        echo "__RicbmK__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __RicbmK__{output}
        getContent __RicbmK__{taskFile} runAfter true | awk '{print "  "__RicbmK__0}' >> __RicbmK__{output}
        
        local env=__RicbmK__(getValue __RicbmK__{taskFile} env)
        sed -e "s/\\__RicbmK__{INNER_PIPELINE_RUN_NAME}/__RicbmK__{innerPipelineRunName}/" \\
            -e "s/\\__RicbmK__{ENV}/__RicbmK__{env}/" \\
            -e "s/\\__RicbmK__{DEPLOY_SUCCESS_WEBHOOK}/__RicbmK__{deploySuccessWebhook}/" \\
            __RicbmK__{MANUAL_TEST_TASK_TEMPLATE} \\
        | awk '{print "    "__RicbmK__0}' >> __RicbmK__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __RicbmK__{pipelineDir} -p
      
      for file in __RicbmK__(find __RicbmK__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__RicbmK__{pipelineDir}/__RicbmK__(basename __RicbmK__file)
        
        validateConfig __RicbmK__file
      
        pipelineHeader __RicbmK__file
      
        pipelineTasks __RicbmK__file
      done
      EOFEOFEOFEOF
      sed -i '/__RicbmK__/s/__RicbmK__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
