apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__ZwH1eX__(params.job-id)"
      - name: generate-name
        value: env-deploy-__ZwH1eX__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __ZwH1eX__(params.pipelines-claim)
            subPath: __ZwH1eX__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__ZwH1eX__(params.job-id)"
          - name: pipelines-claim
            value: "__ZwH1eX__(params.pipelines-claim)"
          - name: env
            value: "__ZwH1eX__{ENV}"
          - name: promotion-name
            value: "__ZwH1eX__(params.promotion-name)"
          - name: env-version
            value: "__ZwH1eX__(params.env-version)"
          - name: repo-full-name
            value: "__ZwH1eX__(params.repo-full-name)"
          - name: repo-ref
            value: "__ZwH1eX__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__ZwH1eX__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __ZwH1eX__(params.manifest-repo-url)
          - name: git-server-http
            value: __ZwH1eX__(params.git-server-http)
          - name: issue-id
            value: "__ZwH1eX__(params.issue-id)"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__ZwH1eX__/s/__ZwH1eX__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__cF8Obs__(params.job-id)"
      - name: env
        value: __cF8Obs__{ENV}
      - name: promotion-name
        value: "__cF8Obs__(params.promotion-name)"
      - name: env-version
        value: "__cF8Obs__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__cF8Obs__/s/__cF8Obs__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__g6o0OH__(params.job-id)"
      - name: generate-name
        value: manual-test-__g6o0OH__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __g6o0OH__(params.pipelines-claim)
            subPath: __g6o0OH__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__g6o0OH__(params.job-id)"
          - name: pipelines-claim
            value: "__g6o0OH__(params.pipelines-claim)"
          - name: env
            value: "__g6o0OH__{ENV}"
          - name: promotion-name
            value: "__g6o0OH__(params.promotion-name)"
          - name: env-version
            value: "__g6o0OH__(params.env-version)"
          - name: repo-full-name
            value: "__g6o0OH__(params.repo-full-name)"
          - name: repo-ref
            value: "__g6o0OH__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__g6o0OH__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __g6o0OH__(params.manifest-repo-url)
          - name: git-server-http
            value: __g6o0OH__(params.git-server-http)
          - name: issue-id
            value: "__g6o0OH__(params.issue-id)"
      EOFEOFEOFEOF
      sed -i '/__g6o0OH__/s/__g6o0OH__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __c4aAWh__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __c4aAWh__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__c4aAWh__/s/__c4aAWh__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__ScLgoY__1  #存储项目中资源配置
      shift
      
      pipelineDir=__ScLgoY__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__ScLgoY__1
        if egrep "^ +taskSpec:" __ScLgoY__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__ScLgoY__1
        
        local pipelineName=__ScLgoY__(basename __ScLgoY__configFile) \\
           && pipelineName=__ScLgoY__{configFile#*pipeline.promotion-} \\
           && pipelineName=__ScLgoY__{pipelineName%.yaml*}
        
        local branchPattern=__ScLgoY__(sed -nr '/^branchPattern: .+__ScLgoY__/ {s/^branchPattern: (.+)__ScLgoY__/\\1/p;q}' __ScLgoY__{configFile})
        if test -z "__ScLgoY__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__ScLgoY__{PROMOTION_NAME}/__ScLgoY__{pipelineName}/" \\
            -e "s/\\__ScLgoY__{BRANCH_PATTERN}/__ScLgoY__{branchPattern}/" \\
            __ScLgoY__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __ScLgoY__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __ScLgoY__{output}
        
        local configFile=__ScLgoY__1
        
        local TEMP_PREFIX="__ScLgoY__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __ScLgoY__{configFile} __ScLgoY__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __ScLgoY__{TEMP_PREFIX}*; do
          local task=__ScLgoY__(getTaskType __ScLgoY__file)
          case __ScLgoY__task in
            env-deploy ) envDeployTask __ScLgoY__file;;
            manual-test ) manualTestTask __ScLgoY__file;;
            env-release ) envReleaseTask __ScLgoY__file;;
            * ) commonTask __ScLgoY__file;;
          esac
        done
        
        rm __ScLgoY__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__ScLgoY__1
        
        if grep "^finally:" 2>&1 >/dev/null __ScLgoY__{configFile}; then
          echo "  finally:" >> __ScLgoY__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__ScLgoY__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __ScLgoY__{configFile} __ScLgoY__{TEMP_PREFIX} finally
        
        local file=""
        for file in __ScLgoY__{TEMP_PREFIX}*; do
          local task=__ScLgoY__(getTaskType __ScLgoY__file)
          case __ScLgoY__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __ScLgoY__file;;
            * ) commonTask __ScLgoY__file;;
          esac
        done
        
        rm __ScLgoY__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__ScLgoY__1
        local tempPreifx=__ScLgoY__2
        local section=__ScLgoY__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__ScLgoY__line"|grep ^- 2>&1 >/dev/null; then
            i=__ScLgoY__(( __ScLgoY__i + 1 ))
            file=__ScLgoY__{tempPreifx}__ScLgoY__i
            touch __ScLgoY__file
          fi
          echo "__ScLgoY__line" >> __ScLgoY__{file}
        done <<EOF
      __ScLgoY__(sed -nr "/^__ScLgoY__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __ScLgoY__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__ScLgoY__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __ScLgoY__{taskFile}
      }
      function getContent() {
        local file=__ScLgoY__1
        local key=__ScLgoY__2
        
        local hasKey=__ScLgoY__3
        local args=
        if test "__ScLgoY__hasKey" == "true"; then
          args="/^  __ScLgoY__key:/{p;d} /^- __ScLgoY__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __ScLgoY__key:/,/^  [a-zA-Z0-9]/{__ScLgoY__args /^  [- ]/p}" __ScLgoY__file
      }
      function getValue() {
        local file=__ScLgoY__1
        local name=__ScLgoY__2
        local prefix="__ScLgoY__3"
        sed -nr "/^__ScLgoY__{prefix}- name: __ScLgoY__{name}/,/^__ScLgoY__{prefix}[^ ]/ {
          /^__ScLgoY__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__ScLgoY__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__ScLgoY__{prefix}    / {
            s/^__ScLgoY__{prefix}  (.*)/\\1/p;
          }
        }" __ScLgoY__{file}
      }
      function addValue() {
        local taskFile=__ScLgoY__1
        local prefix=__ScLgoY__2
        local name=__ScLgoY__3
        local value=__ScLgoY__4
        sed -i "/^__ScLgoY__{prefix}params:/a\\\\__ScLgoY__{prefix}- name: __ScLgoY__{name}\\n__ScLgoY__{prefix}  value: __ScLgoY__{value}" __ScLgoY__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__ScLgoY__1
        if getContent __ScLgoY__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __ScLgoY__{taskFile} \\
        | awk '{print "  "__ScLgoY__0}' >> __ScLgoY__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __ScLgoY__1 __ScLgoY__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __ScLgoY__1 __ScLgoY__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __ScLgoY__1 __ScLgoY__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__ScLgoY__1
        local templateFile=__ScLgoY__2
        
        local name=__ScLgoY__(getContent __ScLgoY__{taskFile} name true)
        local innerPipelineRunName=__ScLgoY__{name#*: }
        
        echo "__ScLgoY__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __ScLgoY__{output}
        getContent __ScLgoY__{taskFile} runAfter true | awk '{print "  "__ScLgoY__0}' >> __ScLgoY__{output}
        
        local env=__ScLgoY__(getValue __ScLgoY__{taskFile} env "  ")
        sed -e "s/\\__ScLgoY__{INNER_PIPELINE_RUN_NAME}/__ScLgoY__{innerPipelineRunName}/" \\
            -e "s/\\__ScLgoY__{ENV}/__ScLgoY__{env}/" \\
            __ScLgoY__{templateFile} \\
        | awk '{print "    "__ScLgoY__0}' >> __ScLgoY__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __ScLgoY__{pipelineDir} -p
      
      for file in __ScLgoY__(find __ScLgoY__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__ScLgoY__{pipelineDir}/__ScLgoY__(basename __ScLgoY__file)
        
        validateConfig __ScLgoY__file
      
        pipelineHeader __ScLgoY__file
      
        pipelineTasks __ScLgoY__file
        
        pipelineFinally __ScLgoY__file
      done
      EOFEOFEOFEOF
      sed -i '/__ScLgoY__/s/__ScLgoY__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output
      $kubectl apply -f ~/output
