apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  - name: promotion-pipelines-namespace
    description: promotion-pipelines 环境命名空间, 默认为当前ns
    default: ""
  - name: promotion-pipeline-namespace
    description: 部署promotion-pipeline到指定命名空间, 默认为当前ns
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)


      promotionPipelinesNs="$(params.promotion-pipelines-namespace)"
      promotionPipelineNs="$(params.promotion-pipeline-namespace)"
      
      if test -z "$promotionPipelinesNs"; then
        promotionPipelinesNs=${namespace}
      fi
      if test -z "$promotionPipelineNs"; then
        promotionPipelineNs=${namespace}
      fi

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__WsWXDi__(params.job-id)"
      - name: namespace
        value: __WsWXDi__{NAMESPACE}
      - name: generate-name
        value: env-deploy-__WsWXDi__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __WsWXDi__(params.pipelines-claim)
            subPath: __WsWXDi__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__WsWXDi__(params.job-id)"
          - name: pipelines-claim
            value: "__WsWXDi__(params.pipelines-claim)"
          - name: env
            value: "__WsWXDi__{ENV}"
          - name: promotion-name
            value: "__WsWXDi__(params.promotion-name)"
          - name: env-version
            value: "__WsWXDi__(params.env-version)"
          - name: repo-full-name
            value: "__WsWXDi__(params.repo-full-name)"
          - name: repo-ref
            value: "__WsWXDi__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__WsWXDi__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __WsWXDi__(params.manifest-repo-url)
          - name: git-server-http
            value: __WsWXDi__(params.git-server-http)
          - name: issue-id
            value: "__WsWXDi__(params.issue-id)"
          - name: deploy-webhook
            value: "__WsWXDi__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__WsWXDi__/s/__WsWXDi__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__WmmsnJ__(params.job-id)"
      - name: env
        value: __WmmsnJ__{ENV}
      - name: promotion-name
        value: "__WmmsnJ__(params.promotion-name)"
      - name: env-version
        value: "__WmmsnJ__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__WmmsnJ__/s/__WmmsnJ__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__zQKCbV__(params.job-id)"
      - name: namespace
        value: __zQKCbV__{NAMESPACE}
      - name: generate-name
        value: manual-test-__zQKCbV__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __zQKCbV__(params.pipelines-claim)
            subPath: __zQKCbV__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__zQKCbV__(params.job-id)"
          - name: pipelines-claim
            value: "__zQKCbV__(params.pipelines-claim)"
          - name: env
            value: "__zQKCbV__{ENV}"
          - name: promotion-name
            value: "__zQKCbV__(params.promotion-name)"
          - name: env-version
            value: "__zQKCbV__(params.env-version)"
          - name: repo-full-name
            value: "__zQKCbV__(params.repo-full-name)"
          - name: repo-ref
            value: "__zQKCbV__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__zQKCbV__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __zQKCbV__(params.manifest-repo-url)
          - name: git-server-http
            value: __zQKCbV__(params.git-server-http)
          - name: issue-id
            value: "__zQKCbV__(params.issue-id)"
          - name: deploy-webhook
            value: "__zQKCbV__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__zQKCbV__/s/__zQKCbV__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __sc0qvv__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __sc0qvv__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__sc0qvv__/s/__sc0qvv__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__XSrJJ8__1  #存储项目中资源配置
      shift
      
      pipelineDir=__XSrJJ8__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__XSrJJ8__1
      shift
      
      promotionPipelinesNamespace=__XSrJJ8__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__XSrJJ8__1
        if egrep "^ +taskSpec:" __XSrJJ8__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__XSrJJ8__1
        
        local pipelineName=__XSrJJ8__(basename __XSrJJ8__configFile) \\
           && pipelineName=__XSrJJ8__{configFile#*pipeline.} \\
           && pipelineName=__XSrJJ8__{pipelineName%.yaml*}
        
        local branchPattern=__XSrJJ8__(sed -nr '/^branchPattern: .+__XSrJJ8__/ {s/^branchPattern: (.+)__XSrJJ8__/\\1/p;q}' __XSrJJ8__{configFile})
        if test -z "__XSrJJ8__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__XSrJJ8__{PROMOTION_NAME}/__XSrJJ8__{pipelineName}/" \\
            -e "s/\\__XSrJJ8__{BRANCH_PATTERN}/__XSrJJ8__{branchPattern}/" \\
            __XSrJJ8__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __XSrJJ8__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __XSrJJ8__{output}
        
        local configFile=__XSrJJ8__1
        
        local TEMP_PREFIX="__XSrJJ8__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __XSrJJ8__{configFile} __XSrJJ8__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __XSrJJ8__{TEMP_PREFIX}*; do
          local task=__XSrJJ8__(getTaskType __XSrJJ8__file)
          case __XSrJJ8__task in
            env-deploy ) envDeployTask __XSrJJ8__file;;
            manual-test ) manualTestTask __XSrJJ8__file;;
            env-release ) envReleaseTask __XSrJJ8__file;;
            * ) commonTask __XSrJJ8__file;;
          esac
        done
        
        rm __XSrJJ8__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__XSrJJ8__1
        
        if grep "^finally:" 2>&1 >/dev/null __XSrJJ8__{configFile}; then
          echo "  finally:" >> __XSrJJ8__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__XSrJJ8__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __XSrJJ8__{configFile} __XSrJJ8__{TEMP_PREFIX} finally
        
        local file=""
        for file in __XSrJJ8__{TEMP_PREFIX}*; do
          local task=__XSrJJ8__(getTaskType __XSrJJ8__file)
          case __XSrJJ8__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __XSrJJ8__file;;
            * ) commonTask __XSrJJ8__file;;
          esac
        done
        
        rm __XSrJJ8__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__XSrJJ8__1
        local tempPreifx=__XSrJJ8__2
        local section=__XSrJJ8__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__XSrJJ8__line"|grep ^- 2>&1 >/dev/null; then
            i=__XSrJJ8__(( __XSrJJ8__i + 1 ))
            file=__XSrJJ8__{tempPreifx}__XSrJJ8__i
            touch __XSrJJ8__file
          fi
          echo "__XSrJJ8__line" >> __XSrJJ8__{file}
        done <<EOF
      __XSrJJ8__(sed -nr "/^__XSrJJ8__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __XSrJJ8__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__XSrJJ8__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __XSrJJ8__{taskFile}
      }
      function getContent() {
        local file=__XSrJJ8__1
        local key=__XSrJJ8__2
        
        local hasKey=__XSrJJ8__3
        local args=
        if test "__XSrJJ8__hasKey" == "true"; then
          args="/^  __XSrJJ8__key:/{p;d} /^- __XSrJJ8__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __XSrJJ8__key:/,/^  [a-zA-Z0-9]/{__XSrJJ8__args /^  [- ]/p}" __XSrJJ8__file
      }
      function getValue() {
        local file=__XSrJJ8__1
        local name=__XSrJJ8__2
        local prefix="__XSrJJ8__3"
        sed -nr "/^__XSrJJ8__{prefix}- name: __XSrJJ8__{name}/,/^__XSrJJ8__{prefix}[^ ]/ {
          /^__XSrJJ8__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__XSrJJ8__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__XSrJJ8__{prefix}    / {
            s/^__XSrJJ8__{prefix}  (.*)/\\1/p;
          }
        }" __XSrJJ8__{file}
      }
      function addValue() {
        local taskFile=__XSrJJ8__1
        local prefix=__XSrJJ8__2
        local name=__XSrJJ8__3
        local value=__XSrJJ8__4
        sed -i "/^__XSrJJ8__{prefix}params:/a\\\\__XSrJJ8__{prefix}- name: __XSrJJ8__{name}\\n__XSrJJ8__{prefix}  value: __XSrJJ8__{value}" __XSrJJ8__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__XSrJJ8__1
        if getContent __XSrJJ8__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __XSrJJ8__{taskFile} \\
        | awk '{print "  "__XSrJJ8__0}' >> __XSrJJ8__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __XSrJJ8__1 __XSrJJ8__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __XSrJJ8__1 __XSrJJ8__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __XSrJJ8__1 __XSrJJ8__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__XSrJJ8__1
        local templateFile=__XSrJJ8__2
        
        local name=__XSrJJ8__(getContent __XSrJJ8__{taskFile} name true)
        local innerPipelineRunName=__XSrJJ8__{name#*: }
        
        echo "__XSrJJ8__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __XSrJJ8__{output}
        getContent __XSrJJ8__{taskFile} runAfter true | awk '{print "  "__XSrJJ8__0}' >> __XSrJJ8__{output}
        
        local env=__XSrJJ8__(getValue __XSrJJ8__{taskFile} env "  ")
        sed -e "s/\\__XSrJJ8__{INNER_PIPELINE_RUN_NAME}/__XSrJJ8__{innerPipelineRunName}/" \\
            -e "s/\\__XSrJJ8__{NAMESPACE}/__XSrJJ8__{promotionPipelinesNamespace}/" \\
            -e "s/\\__XSrJJ8__{ENV}/__XSrJJ8__{env}/" \\
            -e "s/\\__XSrJJ8__{DEPLOY_SUCCESS_WEBHOOK}/__XSrJJ8__{deploySuccessWebhook}/" \\
            __XSrJJ8__{templateFile} \\
        | awk '{print "    "__XSrJJ8__0}' >> __XSrJJ8__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __XSrJJ8__{pipelineDir} -p
      
      for file in __XSrJJ8__(find __XSrJJ8__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__XSrJJ8__{pipelineDir}/__XSrJJ8__(basename __XSrJJ8__file)
        
        validateConfig __XSrJJ8__file
      
        pipelineHeader __XSrJJ8__file
      
        pipelineTasks __XSrJJ8__file
        
        pipelineFinally __XSrJJ8__file
      done
      EOFEOFEOFEOF
      sed -i '/__XSrJJ8__/s/__XSrJJ8__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)' "${promotionPipelinesNs}"
      $kubectl apply -f ~/output -n ${promotionPipelineNs}
