apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__GDht1u__(params.job-id)"
      - name: generate-name
        value: env-deploy-__GDht1u__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __GDht1u__(params.pipelines-claim)
            subPath: __GDht1u__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__GDht1u__(params.job-id)"
          - name: pipelines-claim
            value: "__GDht1u__(params.pipelines-claim)"
          - name: env
            value: "__GDht1u__{ENV}"
          - name: promotion-name
            value: "__GDht1u__(params.promotion-name)"
          - name: env-version
            value: "__GDht1u__(params.env-version)"
          - name: repo-full-name
            value: "__GDht1u__(params.repo-full-name)"
          - name: repo-ref
            value: "__GDht1u__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__GDht1u__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __GDht1u__(params.manifest-repo-url)
          - name: git-server-http
            value: __GDht1u__(params.git-server-http)
          - name: issue-id
            value: "__GDht1u__(params.issue-id)"
          - name: deploy-webhook
            value: "__GDht1u__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__GDht1u__/s/__GDht1u__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__6hXAhh__(params.job-id)"
      - name: env
        value: __6hXAhh__{ENV}
      - name: promotion-name
        value: "__6hXAhh__(params.promotion-name)"
      - name: env-version
        value: "__6hXAhh__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__6hXAhh__/s/__6hXAhh__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__N6ysB3__(params.job-id)"
      - name: generate-name
        value: manual-test-__N6ysB3__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __N6ysB3__(params.pipelines-claim)
            subPath: __N6ysB3__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__N6ysB3__(params.job-id)"
          - name: pipelines-claim
            value: "__N6ysB3__(params.pipelines-claim)"
          - name: env
            value: "__N6ysB3__{ENV}"
          - name: promotion-name
            value: "__N6ysB3__(params.promotion-name)"
          - name: env-version
            value: "__N6ysB3__(params.env-version)"
          - name: repo-full-name
            value: "__N6ysB3__(params.repo-full-name)"
          - name: repo-ref
            value: "__N6ysB3__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__N6ysB3__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __N6ysB3__(params.manifest-repo-url)
          - name: git-server-http
            value: __N6ysB3__(params.git-server-http)
          - name: issue-id
            value: "__N6ysB3__(params.issue-id)"
          - name: deploy-webhook
            value: "__N6ysB3__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__N6ysB3__/s/__N6ysB3__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __GHEm5g__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __GHEm5g__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__GHEm5g__/s/__GHEm5g__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__GB9S2n__1  #存储项目中资源配置
      shift
      
      pipelineDir=__GB9S2n__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__GB9S2n__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__GB9S2n__1
        if egrep "^ +taskSpec:" __GB9S2n__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__GB9S2n__1
        
        local pipelineName=__GB9S2n__(basename __GB9S2n__configFile) \\
           && pipelineName=__GB9S2n__{configFile#*pipeline.promotion-} \\
           && pipelineName=__GB9S2n__{pipelineName%.yaml*}
        
        local branchPattern=__GB9S2n__(sed -nr '/^branchPattern: .+__GB9S2n__/ {s/^branchPattern: (.+)__GB9S2n__/\\1/p;q}' __GB9S2n__{configFile})
        if test -z "__GB9S2n__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__GB9S2n__{PROMOTION_NAME}/__GB9S2n__{pipelineName}/" \\
            -e "s/\\__GB9S2n__{BRANCH_PATTERN}/__GB9S2n__{branchPattern}/" \\
            __GB9S2n__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __GB9S2n__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __GB9S2n__{output}
        
        local configFile=__GB9S2n__1
        
        local TEMP_PREFIX="__GB9S2n__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __GB9S2n__{configFile} __GB9S2n__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __GB9S2n__{TEMP_PREFIX}*; do
          local task=__GB9S2n__(getTaskType __GB9S2n__file)
          case __GB9S2n__task in
            env-deploy ) envDeployTask __GB9S2n__file;;
            manual-test ) manualTestTask __GB9S2n__file;;
            env-release ) envReleaseTask __GB9S2n__file;;
            * ) commonTask __GB9S2n__file;;
          esac
        done
        
        rm __GB9S2n__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__GB9S2n__1
        
        if grep "^finally:" 2>&1 >/dev/null __GB9S2n__{configFile}; then
          echo "  finally:" >> __GB9S2n__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__GB9S2n__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __GB9S2n__{configFile} __GB9S2n__{TEMP_PREFIX} finally
        
        local file=""
        for file in __GB9S2n__{TEMP_PREFIX}*; do
          local task=__GB9S2n__(getTaskType __GB9S2n__file)
          case __GB9S2n__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __GB9S2n__file;;
            * ) commonTask __GB9S2n__file;;
          esac
        done
        
        rm __GB9S2n__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__GB9S2n__1
        local tempPreifx=__GB9S2n__2
        local section=__GB9S2n__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__GB9S2n__line"|grep ^- 2>&1 >/dev/null; then
            i=__GB9S2n__(( __GB9S2n__i + 1 ))
            file=__GB9S2n__{tempPreifx}__GB9S2n__i
            touch __GB9S2n__file
          fi
          echo "__GB9S2n__line" >> __GB9S2n__{file}
        done <<EOF
      __GB9S2n__(sed -nr "/^__GB9S2n__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __GB9S2n__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__GB9S2n__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __GB9S2n__{taskFile}
      }
      function getContent() {
        local file=__GB9S2n__1
        local key=__GB9S2n__2
        
        local hasKey=__GB9S2n__3
        local args=
        if test "__GB9S2n__hasKey" == "true"; then
          args="/^  __GB9S2n__key:/{p;d} /^- __GB9S2n__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __GB9S2n__key:/,/^  [a-zA-Z0-9]/{__GB9S2n__args /^  [- ]/p}" __GB9S2n__file
      }
      function getValue() {
        local file=__GB9S2n__1
        local name=__GB9S2n__2
        local prefix="__GB9S2n__3"
        sed -nr "/^__GB9S2n__{prefix}- name: __GB9S2n__{name}/,/^__GB9S2n__{prefix}[^ ]/ {
          /^__GB9S2n__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__GB9S2n__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__GB9S2n__{prefix}    / {
            s/^__GB9S2n__{prefix}  (.*)/\\1/p;
          }
        }" __GB9S2n__{file}
      }
      function addValue() {
        local taskFile=__GB9S2n__1
        local prefix=__GB9S2n__2
        local name=__GB9S2n__3
        local value=__GB9S2n__4
        sed -i "/^__GB9S2n__{prefix}params:/a\\\\__GB9S2n__{prefix}- name: __GB9S2n__{name}\\n__GB9S2n__{prefix}  value: __GB9S2n__{value}" __GB9S2n__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__GB9S2n__1
        if getContent __GB9S2n__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __GB9S2n__{taskFile} \\
        | awk '{print "  "__GB9S2n__0}' >> __GB9S2n__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __GB9S2n__1 __GB9S2n__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __GB9S2n__1 __GB9S2n__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __GB9S2n__1 __GB9S2n__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__GB9S2n__1
        local templateFile=__GB9S2n__2
        
        local name=__GB9S2n__(getContent __GB9S2n__{taskFile} name true)
        local innerPipelineRunName=__GB9S2n__{name#*: }
        
        echo "__GB9S2n__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __GB9S2n__{output}
        getContent __GB9S2n__{taskFile} runAfter true | awk '{print "  "__GB9S2n__0}' >> __GB9S2n__{output}
        
        local env=__GB9S2n__(getValue __GB9S2n__{taskFile} env "  ")
        sed -e "s/\\__GB9S2n__{INNER_PIPELINE_RUN_NAME}/__GB9S2n__{innerPipelineRunName}/" \\
            -e "s/\\__GB9S2n__{ENV}/__GB9S2n__{env}/" \\
            -e "s/\\__GB9S2n__{DEPLOY_SUCCESS_WEBHOOK}/__GB9S2n__{deploySuccessWebhook}/" \\
            __GB9S2n__{templateFile} \\
        | awk '{print "    "__GB9S2n__0}' >> __GB9S2n__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __GB9S2n__{pipelineDir} -p
      
      for file in __GB9S2n__(find __GB9S2n__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__GB9S2n__{pipelineDir}/__GB9S2n__(basename __GB9S2n__file)
        
        validateConfig __GB9S2n__file
      
        pipelineHeader __GB9S2n__file
      
        pipelineTasks __GB9S2n__file
        
        pipelineFinally __GB9S2n__file
      done
      EOFEOFEOFEOF
      sed -i '/__GB9S2n__/s/__GB9S2n__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
