apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-pipeline-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  - name: promotion-pipelines-namespace
    description: promotion-pipelines 环境命名空间, 默认为当前ns
    default: ""
  - name: promotion-pipeline-namespace
    description: 部署promotion-pipeline到指定命名空间, 默认为当前ns
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)


      promotionPipelinesNs="$(params.promotion-pipelines-namespace)"
      promotionPipelineNs="$(params.promotion-pipeline-namespace)"
      
      if test -z "$promotionPipelinesNs"; then
        promotionPipelinesNs=${namespace}
      fi
      if test -z "$promotionPipelineNs"; then
        promotionPipelineNs=${namespace}
      fi

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__EjpFUv__(params.job-id)"
      - name: namespace
        value: __EjpFUv__{PROMOTION_PIPELINES_NAMESPACE}
      - name: generate-name
        value: env-deploy-__EjpFUv__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __EjpFUv__(params.pipelines-claim)
            subPath: __EjpFUv__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__EjpFUv__(params.job-id)"
          - name: pipelines-claim
            value: "__EjpFUv__(params.pipelines-claim)"
          - name: env
            value: "__EjpFUv__{ENV}"
          - name: promotion-pipeline-namespace
            value: "__EjpFUv__{PROMOTION_PIPELINE_NAMESPACE}"
          - name: promotion-name
            value: "__EjpFUv__(params.promotion-name)"
          - name: env-version
            value: "__EjpFUv__(params.env-version)"
          - name: repo-full-name
            value: "__EjpFUv__(params.repo-full-name)"
          - name: repo-ref
            value: "__EjpFUv__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__EjpFUv__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __EjpFUv__(params.manifest-repo-url)
          - name: git-server-http
            value: __EjpFUv__(params.git-server-http)
          - name: issue-id
            value: "__EjpFUv__(params.issue-id)"
          - name: deploy-webhook
            value: "__EjpFUv__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__EjpFUv__/s/__EjpFUv__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__C2j0z7__(params.job-id)"
      - name: env
        value: __C2j0z7__{ENV}
      - name: promotion-pipeline-namespace
        value: __C2j0z7__{PROMOTION_PIPELINE_NAMESPACE}
      - name: promotion-name
        value: "__C2j0z7__(params.promotion-name)"
      - name: env-version
        value: "__C2j0z7__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__C2j0z7__/s/__C2j0z7__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__Mfi2e0__(params.job-id)"
      - name: namespace
        value: __Mfi2e0__{PROMOTION_PIPELINES_NAMESPACE}
      - name: generate-name
        value: manual-test-__Mfi2e0__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __Mfi2e0__(params.pipelines-claim)
            subPath: __Mfi2e0__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__Mfi2e0__(params.job-id)"
          - name: pipelines-claim
            value: "__Mfi2e0__(params.pipelines-claim)"
          - name: env
            value: "__Mfi2e0__{ENV}"
          - name: promotion-name
            value: "__Mfi2e0__(params.promotion-name)"
          - name: env-version
            value: "__Mfi2e0__(params.env-version)"
          - name: repo-full-name
            value: "__Mfi2e0__(params.repo-full-name)"
          - name: repo-ref
            value: "__Mfi2e0__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__Mfi2e0__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __Mfi2e0__(params.manifest-repo-url)
          - name: git-server-http
            value: __Mfi2e0__(params.git-server-http)
          - name: issue-id
            value: "__Mfi2e0__(params.issue-id)"
          - name: deploy-webhook
            value: "__Mfi2e0__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__Mfi2e0__/s/__Mfi2e0__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __nTcVgB__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __nTcVgB__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__nTcVgB__/s/__nTcVgB__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__4XU7ic__1  #存储项目中资源配置
      shift
      
      pipelineDir=__4XU7ic__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__4XU7ic__1
      shift
      
      promotionPipelinesNamespace=__4XU7ic__1
      promotionPipelineNamespace=__4XU7ic__2
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__4XU7ic__1
        if egrep "^ +taskSpec:" __4XU7ic__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__4XU7ic__1
        
        local pipelineName=__4XU7ic__(basename __4XU7ic__configFile) \\
           && pipelineName=__4XU7ic__{configFile#*pipeline.promotion-} \\
           && pipelineName=__4XU7ic__{pipelineName%.yaml*}
        
        local branchPattern=__4XU7ic__(sed -nr '/^branchPattern: .+__4XU7ic__/ {s/^branchPattern: (.+)__4XU7ic__/\\1/p;q}' __4XU7ic__{configFile})
        if test -z "__4XU7ic__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__4XU7ic__{PROMOTION_NAME}/__4XU7ic__{pipelineName}/" \\
            -e "s/\\__4XU7ic__{BRANCH_PATTERN}/__4XU7ic__{branchPattern}/" \\
            __4XU7ic__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __4XU7ic__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __4XU7ic__{output}
        
        local configFile=__4XU7ic__1
        
        local TEMP_PREFIX="__4XU7ic__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __4XU7ic__{configFile} __4XU7ic__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __4XU7ic__{TEMP_PREFIX}*; do
          local task=__4XU7ic__(getTaskType __4XU7ic__file)
          case __4XU7ic__task in
            env-deploy ) envDeployTask __4XU7ic__file;;
            manual-test ) manualTestTask __4XU7ic__file;;
            env-release ) envReleaseTask __4XU7ic__file;;
            * ) commonTask __4XU7ic__file;;
          esac
        done
        
        rm __4XU7ic__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__4XU7ic__1
        
        if grep "^finally:" 2>&1 >/dev/null __4XU7ic__{configFile}; then
          echo "  finally:" >> __4XU7ic__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__4XU7ic__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __4XU7ic__{configFile} __4XU7ic__{TEMP_PREFIX} finally
        
        local file=""
        for file in __4XU7ic__{TEMP_PREFIX}*; do
          local task=__4XU7ic__(getTaskType __4XU7ic__file)
          case __4XU7ic__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __4XU7ic__file;;
            * ) commonTask __4XU7ic__file;;
          esac
        done
        
        rm __4XU7ic__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__4XU7ic__1
        local tempPreifx=__4XU7ic__2
        local section=__4XU7ic__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__4XU7ic__line"|grep ^- 2>&1 >/dev/null; then
            i=__4XU7ic__(( __4XU7ic__i + 1 ))
            file=__4XU7ic__{tempPreifx}__4XU7ic__i
            touch __4XU7ic__file
          fi
          echo "__4XU7ic__line" >> __4XU7ic__{file}
        done <<EOF
      __4XU7ic__(sed -nr "/^__4XU7ic__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __4XU7ic__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__4XU7ic__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __4XU7ic__{taskFile}
      }
      function getContent() {
        local file=__4XU7ic__1
        local key=__4XU7ic__2
        
        local hasKey=__4XU7ic__3
        local args=
        if test "__4XU7ic__hasKey" == "true"; then
          args="/^  __4XU7ic__key:/{p;d} /^- __4XU7ic__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __4XU7ic__key:/,/^  [a-zA-Z0-9]/{__4XU7ic__args /^  [- ]/p}" __4XU7ic__file
      }
      function getValue() {
        local file=__4XU7ic__1
        local name=__4XU7ic__2
        local prefix="__4XU7ic__3"
        sed -nr "/^__4XU7ic__{prefix}- name: __4XU7ic__{name}/,/^__4XU7ic__{prefix}[^ ]/ {
          /^__4XU7ic__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__4XU7ic__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__4XU7ic__{prefix}    / {
            s/^__4XU7ic__{prefix}  (.*)/\\1/p;
          }
        }" __4XU7ic__{file}
      }
      function addValue() {
        local taskFile=__4XU7ic__1
        local prefix=__4XU7ic__2
        local name=__4XU7ic__3
        local value=__4XU7ic__4
        sed -i "/^__4XU7ic__{prefix}params:/a\\\\__4XU7ic__{prefix}- name: __4XU7ic__{name}\\n__4XU7ic__{prefix}  value: __4XU7ic__{value}" __4XU7ic__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__4XU7ic__1
        if getContent __4XU7ic__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __4XU7ic__{taskFile} \\
        | awk '{print "  "__4XU7ic__0}' >> __4XU7ic__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __4XU7ic__1 __4XU7ic__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __4XU7ic__1 __4XU7ic__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __4XU7ic__1 __4XU7ic__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__4XU7ic__1
        local templateFile=__4XU7ic__2
        
        local name=__4XU7ic__(getContent __4XU7ic__{taskFile} name true)
        local innerPipelineRunName=__4XU7ic__{name#*: }
        
        echo "__4XU7ic__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __4XU7ic__{output}
        getContent __4XU7ic__{taskFile} runAfter true | awk '{print "  "__4XU7ic__0}' >> __4XU7ic__{output}
        
        local env=__4XU7ic__(getValue __4XU7ic__{taskFile} env "  ")
        sed -e "s/\\__4XU7ic__{INNER_PIPELINE_RUN_NAME}/__4XU7ic__{innerPipelineRunName}/" \\
            -e "s/\\__4XU7ic__{PROMOTION_PIPELINES_NAMESPACE}/__4XU7ic__{promotionPipelinesNamespace}/" \\
            -e "s/\\__4XU7ic__{PROMOTION_PIPELINE_NAMESPACE}/__4XU7ic__{promotionPipelineNamespace}/" \\
            -e "s/\\__4XU7ic__{ENV}/__4XU7ic__{env}/" \\
            -e "s/\\__4XU7ic__{DEPLOY_SUCCESS_WEBHOOK}/__4XU7ic__{deploySuccessWebhook}/" \\
            __4XU7ic__{templateFile} \\
        | awk '{print "    "__4XU7ic__0}' >> __4XU7ic__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __4XU7ic__{pipelineDir} -p
      
      for file in __4XU7ic__(find __4XU7ic__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__4XU7ic__{pipelineDir}/__4XU7ic__(basename __4XU7ic__file)
        
        validateConfig __4XU7ic__file
      
        pipelineHeader __4XU7ic__file
      
        pipelineTasks __4XU7ic__file
        
        pipelineFinally __4XU7ic__file
      done
      EOFEOFEOFEOF
      sed -i '/__4XU7ic__/s/__4XU7ic__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)' "${promotionPipelinesNs}" "${promotionPipelineNs}"
      $kubectl apply -f ~/output -n ${promotionPipelineNs}
