apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__2xRdVA__(params.job-id)"
      - name: generate-name
        value: env-deploy-__2xRdVA__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __2xRdVA__(params.pipelines-claim)
            subPath: __2xRdVA__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__2xRdVA__(params.job-id)"
          - name: pipelines-claim
            value: "__2xRdVA__(params.pipelines-claim)"
          - name: env
            value: "__2xRdVA__{ENV}"
          - name: promotion-name
            value: "__2xRdVA__(params.promotion-name)"
          - name: env-version
            value: "__2xRdVA__(params.env-version)"
          - name: repo-full-name
            value: "__2xRdVA__(params.repo-full-name)"
          - name: repo-ref
            value: "__2xRdVA__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__2xRdVA__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __2xRdVA__(params.manifest-repo-url)
          - name: git-server-http
            value: __2xRdVA__(params.git-server-http)
          - name: issue-id
            value: "__2xRdVA__(params.issue-id)"
          - name: deploy-webhook
            value: "__2xRdVA__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__2xRdVA__/s/__2xRdVA__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__gTVpBh__(params.job-id)"
      - name: generate-name
        value: manual-test-__gTVpBh__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __gTVpBh__(params.pipelines-claim)
            subPath: __gTVpBh__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__gTVpBh__(params.job-id)"
          - name: pipelines-claim
            value: "__gTVpBh__(params.pipelines-claim)"
          - name: env
            value: "__gTVpBh__{ENV}"
          - name: promotion-name
            value: "__gTVpBh__(params.promotion-name)"
          - name: env-version
            value: "__gTVpBh__(params.env-version)"
          - name: repo-full-name
            value: "__gTVpBh__(params.repo-full-name)"
          - name: repo-ref
            value: "__gTVpBh__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__gTVpBh__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __gTVpBh__(params.manifest-repo-url)
          - name: git-server-http
            value: __gTVpBh__(params.git-server-http)
          - name: issue-id
            value: "__gTVpBh__(params.issue-id)"
          - name: deploy-webhook
            value: "__gTVpBh__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__gTVpBh__/s/__gTVpBh__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __i0s2n2__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __i0s2n2__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__i0s2n2__/s/__i0s2n2__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__5Z33ka__1  #存储项目中资源配置
      shift
      
      pipelineDir=__5Z33ka__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__5Z33ka__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__5Z33ka__1
        if egrep "^ +taskSpec:" __5Z33ka__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__5Z33ka__1
        
        local pipelineName=__5Z33ka__(basename __5Z33ka__configFile) \\
           && pipelineName=__5Z33ka__{configFile#*pipeline.} \\
           && pipelineName=__5Z33ka__{pipelineName%.yaml*}
        
        local branchPattern=__5Z33ka__(sed -nr '/^branchPattern: .+__5Z33ka__/ {s/^branchPattern: (.+)__5Z33ka__/\\1/p;q}' __5Z33ka__{configFile})
        if test -z "__5Z33ka__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__5Z33ka__{PROMOTION_NAME}/__5Z33ka__{pipelineName}/" \\
            -e "s/\\__5Z33ka__{BRANCH_PATTERN}/__5Z33ka__{branchPattern}/" \\
            __5Z33ka__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __5Z33ka__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __5Z33ka__{output}
        
        local configFile=__5Z33ka__1
        
        local TEMP_PREFIX="__5Z33ka__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __5Z33ka__{configFile} __5Z33ka__{TEMP_PREFIX}
        
        local file=""
        for file in __5Z33ka__{TEMP_PREFIX}*; do
          local task=__5Z33ka__(getTaskType __5Z33ka__file)
          case __5Z33ka__task in
            env-deploy ) envDeployTask __5Z33ka__file;;
            manual-test ) manualTestTask __5Z33ka__file;;
            * ) commonTask __5Z33ka__file;;
          esac
        done
        
        rm __5Z33ka__{TEMP_PREFIX}* -f
      }
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__5Z33ka__1
        local tempPreifx=__5Z33ka__2
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__5Z33ka__line"|grep ^- 2>&1 >/dev/null; then
            i=__5Z33ka__(( __5Z33ka__i + 1 ))
            file=__5Z33ka__{tempPreifx}__5Z33ka__i
            touch __5Z33ka__file
          fi
          echo "__5Z33ka__line" >> __5Z33ka__{file}
        done <<EOF
      __5Z33ka__(sed -nr '/^tasks:/,/^[a-zA-Z0-9]/ {/^[- ]/p}' __5Z33ka__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__5Z33ka__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __5Z33ka__{taskFile}
      }
      function getContent() {
        local file=__5Z33ka__1
        local key=__5Z33ka__2
        
        local hasKey=__5Z33ka__3
        local args=
        if test "__5Z33ka__hasKey" == "true"; then
          args="/^  __5Z33ka__key:/{p;d} /^- __5Z33ka__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __5Z33ka__key:/,/^  [a-zA-Z0-9]/{__5Z33ka__args /^  [- ]/p}" __5Z33ka__file
      }
      function getValue() {
        local file=__5Z33ka__1
        local name=__5Z33ka__2
        local prefix="__5Z33ka__3"
        sed -nr "/^__5Z33ka__{prefix}- name: __5Z33ka__{name}/,/^__5Z33ka__{prefix}[^ ]/ {
          /^__5Z33ka__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__5Z33ka__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__5Z33ka__{prefix}    / {
            s/^__5Z33ka__{prefix}  (.*)/\\1/p;
          }
        }" __5Z33ka__{file}
      }
      
      function commonTask() {
        local taskFile=__5Z33ka__1
        if getContent __5Z33ka__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __5Z33ka__{taskFile} \\
        | awk '{print "  "__5Z33ka__0}' >> __5Z33ka__{output}
      }
      
      function envDeployTask() {
        deployedTestTask __5Z33ka__1 __5Z33ka__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __5Z33ka__1 __5Z33ka__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__5Z33ka__1
        local templateFile=__5Z33ka__2
        
        local name=__5Z33ka__(getContent __5Z33ka__{taskFile} name true)
        local innerPipelineRunName=__5Z33ka__{name#*: }
        
        echo "__5Z33ka__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __5Z33ka__{output}
        getContent __5Z33ka__{taskFile} runAfter true | awk '{print "  "__5Z33ka__0}' >> __5Z33ka__{output}
        
        local env=__5Z33ka__(getValue __5Z33ka__{taskFile} env "  ")
        sed -e "s/\\__5Z33ka__{INNER_PIPELINE_RUN_NAME}/__5Z33ka__{innerPipelineRunName}/" \\
            -e "s/\\__5Z33ka__{ENV}/__5Z33ka__{env}/" \\
            -e "s/\\__5Z33ka__{DEPLOY_SUCCESS_WEBHOOK}/__5Z33ka__{deploySuccessWebhook}/" \\
            __5Z33ka__{templateFile} \\
        | awk '{print "    "__5Z33ka__0}' >> __5Z33ka__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __5Z33ka__{pipelineDir} -p
      
      for file in __5Z33ka__(find __5Z33ka__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__5Z33ka__{pipelineDir}/__5Z33ka__(basename __5Z33ka__file)
        
        validateConfig __5Z33ka__file
      
        pipelineHeader __5Z33ka__file
      
        pipelineTasks __5Z33ka__file
      done
      EOFEOFEOFEOF
      sed -i '/__5Z33ka__/s/__5Z33ka__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)'
      $kubectl apply -f ~/output
