apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-pipeline-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  - name: deploy-success-webhook
    description: 部署成功通知地址, 用于需部署后测试的任务
    default: ""
  - name: promotion-pipelines-namespace
    description: promotion-pipelines 环境命名空间, 默认为当前ns
    default: ""
  - name: promotion-pipeline-namespace
    description: 部署promotion-pipeline到指定命名空间, 默认为当前ns
    default: ""
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)


      promotionPipelinesNs="$(params.promotion-pipelines-namespace)"
      promotionPipelineNs="$(params.promotion-pipeline-namespace)"
      
      if test -z "$promotionPipelinesNs"; then
        promotionPipelinesNs=${namespace}
      fi
      if test -z "$promotionPipelineNs"; then
        promotionPipelineNs=${namespace}
      fi

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__JPlLTg__(params.job-id)"
      - name: namespace
        value: __JPlLTg__{NAMESPACE}
      - name: generate-name
        value: env-deploy-__JPlLTg__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __JPlLTg__(params.pipelines-claim)
            subPath: __JPlLTg__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__JPlLTg__(params.job-id)"
          - name: pipelines-claim
            value: "__JPlLTg__(params.pipelines-claim)"
          - name: env
            value: "__JPlLTg__{ENV}"
          - name: promotion-name
            value: "__JPlLTg__(params.promotion-name)"
          - name: env-version
            value: "__JPlLTg__(params.env-version)"
          - name: repo-full-name
            value: "__JPlLTg__(params.repo-full-name)"
          - name: repo-ref
            value: "__JPlLTg__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__JPlLTg__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __JPlLTg__(params.manifest-repo-url)
          - name: git-server-http
            value: __JPlLTg__(params.git-server-http)
          - name: issue-id
            value: "__JPlLTg__(params.issue-id)"
          - name: deploy-webhook
            value: "__JPlLTg__{DEPLOY_SUCCESS_WEBHOOK}"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__JPlLTg__/s/__JPlLTg__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__pWrbyN__(params.job-id)"
      - name: env
        value: __pWrbyN__{ENV}
      - name: promotion-name
        value: "__pWrbyN__(params.promotion-name)"
      - name: env-version
        value: "__pWrbyN__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__pWrbyN__/s/__pWrbyN__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__m4B88B__(params.job-id)"
      - name: namespace
        value: __m4B88B__{NAMESPACE}
      - name: generate-name
        value: manual-test-__m4B88B__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __m4B88B__(params.pipelines-claim)
            subPath: __m4B88B__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__m4B88B__(params.job-id)"
          - name: pipelines-claim
            value: "__m4B88B__(params.pipelines-claim)"
          - name: env
            value: "__m4B88B__{ENV}"
          - name: promotion-name
            value: "__m4B88B__(params.promotion-name)"
          - name: env-version
            value: "__m4B88B__(params.env-version)"
          - name: repo-full-name
            value: "__m4B88B__(params.repo-full-name)"
          - name: repo-ref
            value: "__m4B88B__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__m4B88B__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __m4B88B__(params.manifest-repo-url)
          - name: git-server-http
            value: __m4B88B__(params.git-server-http)
          - name: issue-id
            value: "__m4B88B__(params.issue-id)"
          - name: deploy-webhook
            value: "__m4B88B__{DEPLOY_SUCCESS_WEBHOOK}"
      EOFEOFEOFEOF
      sed -i '/__m4B88B__/s/__m4B88B__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __JBEvMT__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __JBEvMT__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__JBEvMT__/s/__JBEvMT__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__OeQmgk__1  #存储项目中资源配置
      shift
      
      pipelineDir=__OeQmgk__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      deploySuccessWebhook=__OeQmgk__1
      shift
      
      promotionPipelinesNamespace=__OeQmgk__1
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__OeQmgk__1
        if egrep "^ +taskSpec:" __OeQmgk__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__OeQmgk__1
        
        local pipelineName=__OeQmgk__(basename __OeQmgk__configFile) \\
           && pipelineName=__OeQmgk__{configFile#*pipeline.promotion-} \\
           && pipelineName=__OeQmgk__{pipelineName%.yaml*}
        
        local branchPattern=__OeQmgk__(sed -nr '/^branchPattern: .+__OeQmgk__/ {s/^branchPattern: (.+)__OeQmgk__/\\1/p;q}' __OeQmgk__{configFile})
        if test -z "__OeQmgk__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__OeQmgk__{PROMOTION_NAME}/__OeQmgk__{pipelineName}/" \\
            -e "s/\\__OeQmgk__{BRANCH_PATTERN}/__OeQmgk__{branchPattern}/" \\
            __OeQmgk__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __OeQmgk__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __OeQmgk__{output}
        
        local configFile=__OeQmgk__1
        
        local TEMP_PREFIX="__OeQmgk__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __OeQmgk__{configFile} __OeQmgk__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __OeQmgk__{TEMP_PREFIX}*; do
          local task=__OeQmgk__(getTaskType __OeQmgk__file)
          case __OeQmgk__task in
            env-deploy ) envDeployTask __OeQmgk__file;;
            manual-test ) manualTestTask __OeQmgk__file;;
            env-release ) envReleaseTask __OeQmgk__file;;
            * ) commonTask __OeQmgk__file;;
          esac
        done
        
        rm __OeQmgk__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__OeQmgk__1
        
        if grep "^finally:" 2>&1 >/dev/null __OeQmgk__{configFile}; then
          echo "  finally:" >> __OeQmgk__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__OeQmgk__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __OeQmgk__{configFile} __OeQmgk__{TEMP_PREFIX} finally
        
        local file=""
        for file in __OeQmgk__{TEMP_PREFIX}*; do
          local task=__OeQmgk__(getTaskType __OeQmgk__file)
          case __OeQmgk__task in
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __OeQmgk__file;;
            * ) commonTask __OeQmgk__file;;
          esac
        done
        
        rm __OeQmgk__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__OeQmgk__1
        local tempPreifx=__OeQmgk__2
        local section=__OeQmgk__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__OeQmgk__line"|grep ^- 2>&1 >/dev/null; then
            i=__OeQmgk__(( __OeQmgk__i + 1 ))
            file=__OeQmgk__{tempPreifx}__OeQmgk__i
            touch __OeQmgk__file
          fi
          echo "__OeQmgk__line" >> __OeQmgk__{file}
        done <<EOF
      __OeQmgk__(sed -nr "/^__OeQmgk__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __OeQmgk__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__OeQmgk__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __OeQmgk__{taskFile}
      }
      function getContent() {
        local file=__OeQmgk__1
        local key=__OeQmgk__2
        
        local hasKey=__OeQmgk__3
        local args=
        if test "__OeQmgk__hasKey" == "true"; then
          args="/^  __OeQmgk__key:/{p;d} /^- __OeQmgk__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __OeQmgk__key:/,/^  [a-zA-Z0-9]/{__OeQmgk__args /^  [- ]/p}" __OeQmgk__file
      }
      function getValue() {
        local file=__OeQmgk__1
        local name=__OeQmgk__2
        local prefix="__OeQmgk__3"
        sed -nr "/^__OeQmgk__{prefix}- name: __OeQmgk__{name}/,/^__OeQmgk__{prefix}[^ ]/ {
          /^__OeQmgk__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__OeQmgk__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__OeQmgk__{prefix}    / {
            s/^__OeQmgk__{prefix}  (.*)/\\1/p;
          }
        }" __OeQmgk__{file}
      }
      function addValue() {
        local taskFile=__OeQmgk__1
        local prefix=__OeQmgk__2
        local name=__OeQmgk__3
        local value=__OeQmgk__4
        sed -i "/^__OeQmgk__{prefix}params:/a\\\\__OeQmgk__{prefix}- name: __OeQmgk__{name}\\n__OeQmgk__{prefix}  value: __OeQmgk__{value}" __OeQmgk__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__OeQmgk__1
        if getContent __OeQmgk__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __OeQmgk__{taskFile} \\
        | awk '{print "  "__OeQmgk__0}' >> __OeQmgk__{output}
      }
      
      function envReleaseTask() {
        deployedTestTask __OeQmgk__1 __OeQmgk__{ENV_RELEASE_TASK_TEMPLATE}
      }
      
      function envDeployTask() {
        deployedTestTask __OeQmgk__1 __OeQmgk__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      
      function manualTestTask() {
        deployedTestTask __OeQmgk__1 __OeQmgk__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTestTask() {
        local taskFile=__OeQmgk__1
        local templateFile=__OeQmgk__2
        
        local name=__OeQmgk__(getContent __OeQmgk__{taskFile} name true)
        local innerPipelineRunName=__OeQmgk__{name#*: }
        
        echo "__OeQmgk__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __OeQmgk__{output}
        getContent __OeQmgk__{taskFile} runAfter true | awk '{print "  "__OeQmgk__0}' >> __OeQmgk__{output}
        
        local env=__OeQmgk__(getValue __OeQmgk__{taskFile} env "  ")
        sed -e "s/\\__OeQmgk__{INNER_PIPELINE_RUN_NAME}/__OeQmgk__{innerPipelineRunName}/" \\
            -e "s/\\__OeQmgk__{NAMESPACE}/__OeQmgk__{promotionPipelinesNamespace}/" \\
            -e "s/\\__OeQmgk__{ENV}/__OeQmgk__{env}/" \\
            -e "s/\\__OeQmgk__{DEPLOY_SUCCESS_WEBHOOK}/__OeQmgk__{deploySuccessWebhook}/" \\
            __OeQmgk__{templateFile} \\
        | awk '{print "    "__OeQmgk__0}' >> __OeQmgk__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __OeQmgk__{pipelineDir} -p
      
      for file in __OeQmgk__(find __OeQmgk__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__OeQmgk__{pipelineDir}/__OeQmgk__(basename __OeQmgk__file)
        
        validateConfig __OeQmgk__file
      
        pipelineHeader __OeQmgk__file
      
        pipelineTasks __OeQmgk__file
        
        pipelineFinally __OeQmgk__file
      done
      EOFEOFEOFEOF
      sed -i '/__OeQmgk__/s/__OeQmgk__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output '$(params.deploy-success-webhook)' "${promotionPipelinesNs}"
      $kubectl apply -f ~/output -n ${promotionPipelineNs}
