apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - pipelineruns
  - taskruns
  verbs:
  - create
  - list
  - get
  - patch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promotion-pipelines:pipeline
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - create
  - list
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods/portforward
  verbs:
  - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promotion-pipelines:pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promotion-pipelines:pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: ${NAMESPACE}
