apiVersion: v1
data:
  common-kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    #resources:
    #- deploy.yaml
  script.sh: |
    srcRootPath=$1

    function cpResoruces() {
      local type=$1
      local length=$(( ${#type} + 1 ))
      local path=$2
      for f in ${type}-*.yaml; do
        cp ${f} ${path}/${f:${length}}
      done
    }

    commonPath=${srcRootPath}/common
    if test ! -d ${commonPath} && mkdir ${commonPath}; then
      cpResoruces common ${commonPath}
    fi
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: project-init-resources
