apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__xMjF8c__(params.job-id)"
      - name: generate-name
        value: env-deploy-__xMjF8c__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __xMjF8c__(params.pipelines-claim)
            subPath: __xMjF8c__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__xMjF8c__(params.job-id)"
          - name: pipelines-claim
            value: "__xMjF8c__(params.pipelines-claim)"
          - name: env
            value: "__xMjF8c__{ENV}"
          - name: promotion-name
            value: "__xMjF8c__(params.promotion-name)"
          - name: env-version
            value: "__xMjF8c__(params.env-version)"
          - name: repo-full-name
            value: "__xMjF8c__(params.repo-full-name)"
          - name: repo-ref
            value: "__xMjF8c__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__xMjF8c__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __xMjF8c__(params.manifest-repo-url)
          - name: deploy-image-names
            value: "__xMjF8c__{DEPLOY_IMAGE_NAMES}"
          - name: deploy-image-tag-pattern
            value: "__xMjF8c__{DEPLOY_IMAGE_TAG_PATTERN}"
          - name: git-server-http
            value: __xMjF8c__(params.git-server-http)
          - name: issue-id
            value: "__xMjF8c__(params.issue-id)"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__xMjF8c__/s/__xMjF8c__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__IL4uPM__(params.job-id)"
      - name: env
        value: __IL4uPM__{ENV}
      - name: promotion-name
        value: "__IL4uPM__(params.promotion-name)"
      - name: env-version
        value: "__IL4uPM__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__IL4uPM__/s/__IL4uPM__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > image-build-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: image-build
      params:
      - name: dest-prefix
        value: 10.1.40.43:5000/__DFkOda__(params.repo-full-name)/
      - name: dest-suffix
        value: ":__DFkOda__(params.repo-ref)"
      - name: insecure-registry
        value: 10.1.40.43:5000
      workspaces:
      - name: source
        workspace: pipeline
        subPath: temporary/project-repo
      EOFEOFEOFEOF
      sed -i '/__DFkOda__/s/__DFkOda__/$/g' image-build-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__A2EpoG__(params.job-id)"
      - name: generate-name
        value: manual-test-__A2EpoG__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __A2EpoG__(params.pipelines-claim)
            subPath: __A2EpoG__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__A2EpoG__(params.job-id)"
          - name: pipelines-claim
            value: "__A2EpoG__(params.pipelines-claim)"
          - name: env
            value: "__A2EpoG__{ENV}"
          - name: promotion-name
            value: "__A2EpoG__(params.promotion-name)"
          - name: env-version
            value: "__A2EpoG__(params.env-version)"
          - name: repo-full-name
            value: "__A2EpoG__(params.repo-full-name)"
          - name: repo-ref
            value: "__A2EpoG__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__A2EpoG__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __A2EpoG__(params.manifest-repo-url)
          - name: git-server-http
            value: __A2EpoG__(params.git-server-http)
          - name: issue-id
            value: "__A2EpoG__(params.issue-id)"
      EOFEOFEOFEOF
      sed -i '/__A2EpoG__/s/__A2EpoG__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __OZdWkt__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __OZdWkt__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__OZdWkt__/s/__OZdWkt__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      IMAGE_BUILD_TASK_TEMPLATE="image-build-task-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__DEDh8p__1  #存储项目中资源配置
      shift
      
      pipelineDir=__DEDh8p__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__DEDh8p__1
        if egrep "^ +taskSpec:" __DEDh8p__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__DEDh8p__1
        
        local pipelineName=__DEDh8p__(basename __DEDh8p__configFile) \\
           && pipelineName=__DEDh8p__{configFile#*pipeline.promotion-} \\
           && pipelineName=__DEDh8p__{pipelineName%.yaml*}
        
        local branchPattern=__DEDh8p__(sed -nr '/^branchPattern: .+__DEDh8p__/ {s/^branchPattern: (.+)__DEDh8p__/\\1/p;q}' __DEDh8p__{configFile})
        if test -z "__DEDh8p__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__DEDh8p__{PROMOTION_NAME}/__DEDh8p__{pipelineName}/" \\
            -e "s/\\__DEDh8p__{BRANCH_PATTERN}/__DEDh8p__{branchPattern}/" \\
            __DEDh8p__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __DEDh8p__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __DEDh8p__{output}
        
        local configFile=__DEDh8p__1
        
        local TEMP_PREFIX="__DEDh8p__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __DEDh8p__{configFile} __DEDh8p__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __DEDh8p__{TEMP_PREFIX}*; do
          local task=__DEDh8p__(getTaskType __DEDh8p__file)
          case __DEDh8p__task in
            image-build ) imageBuildTask __DEDh8p__file;;
            env-deploy ) envDeployTask __DEDh8p__file;;
            manual-test ) manualTestTask __DEDh8p__file;;
            env-release ) envReleaseTask __DEDh8p__file;;
            * ) commonTask __DEDh8p__file;;
          esac
        done
        
        rm __DEDh8p__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__DEDh8p__1
        
        if grep "^finally:" 2>&1 >/dev/null __DEDh8p__{configFile}; then
          echo "  finally:" >> __DEDh8p__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__DEDh8p__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __DEDh8p__{configFile} __DEDh8p__{TEMP_PREFIX} finally
        
        local file=""
        for file in __DEDh8p__{TEMP_PREFIX}*; do
          local task=__DEDh8p__(getTaskType __DEDh8p__file)
          case __DEDh8p__task in
            image-build ) return 1;;
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __DEDh8p__file;;
            * ) commonTask __DEDh8p__file;;
          esac
        done
        
        rm __DEDh8p__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__DEDh8p__1
        local tempPreifx=__DEDh8p__2
        local section=__DEDh8p__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__DEDh8p__line"|grep ^- 2>&1 >/dev/null; then
            i=__DEDh8p__(( __DEDh8p__i + 1 ))
            file=__DEDh8p__{tempPreifx}__DEDh8p__i
            touch __DEDh8p__file
          fi
          echo "__DEDh8p__line" >> __DEDh8p__{file}
        done <<EOF
      __DEDh8p__(sed -nr "/^__DEDh8p__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __DEDh8p__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__DEDh8p__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __DEDh8p__{taskFile}
      }
      function getContent() {
        local file=__DEDh8p__1
        local key=__DEDh8p__2
        
        local hasKey=__DEDh8p__3
        local args=
        if test "__DEDh8p__hasKey" == "true"; then
          args="/^  __DEDh8p__key:/{p;d} /^- __DEDh8p__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __DEDh8p__key:/,/^  [a-zA-Z0-9]/{__DEDh8p__args /^  [- ]/p}" __DEDh8p__file
      }
      function getValue() {
        local file=__DEDh8p__1
        local name=__DEDh8p__2
        local prefix="__DEDh8p__3"
        sed -nr "/^__DEDh8p__{prefix}- name: __DEDh8p__{name}/,/^__DEDh8p__{prefix}[^ ]/ {
          /^__DEDh8p__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__DEDh8p__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__DEDh8p__{prefix}    / {
            s/^__DEDh8p__{prefix}  (.*)/\\1/p;
          }
        }" __DEDh8p__{file}
      }
      function addValue() {
        local taskFile=__DEDh8p__1
        local prefix=__DEDh8p__2
        local name=__DEDh8p__3
        local value=__DEDh8p__4
        sed -i "/^__DEDh8p__{prefix}params:/a\\\\__DEDh8p__{prefix}- name: __DEDh8p__{name}\\n__DEDh8p__{prefix}  value: __DEDh8p__{value}" __DEDh8p__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__DEDh8p__1
        if getContent __DEDh8p__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __DEDh8p__{taskFile} \\
        | awk '{print "  "__DEDh8p__0}' >> __DEDh8p__{output}
      }
      
      function imageBuildTask() {
        deployedTaskByTemplate __DEDh8p__1 __DEDh8p__{IMAGE_BUILD_TASK_TEMPLATE}
      }
      function envReleaseTask() {
        deployedTaskByTemplate __DEDh8p__1 __DEDh8p__{ENV_RELEASE_TASK_TEMPLATE}
      }
      function envDeployTask() {
        deployedTaskByTemplate __DEDh8p__1 __DEDh8p__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      function manualTestTask() {
        deployedTaskByTemplate __DEDh8p__1 __DEDh8p__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTaskByTemplate() {
        local taskFile=__DEDh8p__1
        local templateFile=__DEDh8p__2
        
        local name=__DEDh8p__(getContent __DEDh8p__{taskFile} name true)
        local innerPipelineRunName=__DEDh8p__{name#*: }
        
        echo "__DEDh8p__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __DEDh8p__{output}
        getContent __DEDh8p__{taskFile} runAfter true | awk '{print "  "__DEDh8p__0}' >> __DEDh8p__{output}
        
        local env=__DEDh8p__(getValue __DEDh8p__{taskFile} env "  ")
        local deployImageNames=__DEDh8p__(getValue __DEDh8p__{taskFile} deploy-image-names "  ")
        local deployImageTagPattern='__DEDh8p__(params.repo-ref)'
        sed -e "s/\\__DEDh8p__{INNER_PIPELINE_RUN_NAME}/__DEDh8p__{innerPipelineRunName}/" \\
            -e "s/\\__DEDh8p__{ENV}/__DEDh8p__{env}/" \\
            -e "s/\\__DEDh8p__{DEPLOY_IMAGE_NAMES}/__DEDh8p__{deployImageNames}/" \\
            -e "s/\\__DEDh8p__{DEPLOY_IMAGE_TAG_PATTERN}/__DEDh8p__{deployImageTagPattern}/" \\
            __DEDh8p__{templateFile} \\
        | awk '{print "    "__DEDh8p__0}' >> __DEDh8p__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __DEDh8p__{pipelineDir} -p
      
      for file in __DEDh8p__(find __DEDh8p__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__DEDh8p__{pipelineDir}/__DEDh8p__(basename __DEDh8p__file)
        
        validateConfig __DEDh8p__file
      
        pipelineHeader __DEDh8p__file
      
        pipelineTasks __DEDh8p__file
        
        pipelineFinally __DEDh8p__file
      done
      EOFEOFEOFEOF
      sed -i '/__DEDh8p__/s/__DEDh8p__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output
      $kubectl apply -f ~/output
