apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__tlQytl__(params.job-id)"
      - name: generate-name
        value: env-deploy-__tlQytl__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __tlQytl__(params.pipelines-claim)
            subPath: __tlQytl__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__tlQytl__(params.job-id)"
          - name: pipelines-claim
            value: "__tlQytl__(params.pipelines-claim)"
          - name: env
            value: "__tlQytl__{ENV}"
          - name: promotion-name
            value: "__tlQytl__(params.promotion-name)"
          - name: env-version
            value: "__tlQytl__(params.env-version)"
          - name: repo-full-name
            value: "__tlQytl__(params.repo-full-name)"
          - name: repo-ref
            value: "__tlQytl__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__tlQytl__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __tlQytl__(params.manifest-repo-url)
          - name: deploy-image-names
            value: "__tlQytl__{DEPLOY_IMAGE_NAMES}"
          - name: deploy-image-tag-pattern
            value: "__tlQytl__{DEPLOY_IMAGE_TAG_PATTERN}"
          - name: git-server-http
            value: __tlQytl__(params.git-server-http)
          - name: issue-id
            value: "__tlQytl__(params.issue-id)"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__tlQytl__/s/__tlQytl__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__UjHDnc__(params.job-id)"
      - name: env
        value: __UjHDnc__{ENV}
      - name: promotion-name
        value: "__UjHDnc__(params.promotion-name)"
      - name: env-version
        value: "__UjHDnc__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__UjHDnc__/s/__UjHDnc__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > image-build-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: image-build
      params:
      - name: dest-prefix
        value: 10.1.40.43:5000/__etGitR__(params.repo-full-name)/
      - name: dest-suffix
        value: ":__etGitR__(params.repo-ref)"
      - name: insecure-registry
        value: 10.1.40.43:5000
      workspaces:
      - name: source
        workspace: pipeline
        subPath: temporary/project-repo
      EOFEOFEOFEOF
      sed -i '/__etGitR__/s/__etGitR__/$/g' image-build-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__9Zi6G8__(params.job-id)"
      - name: generate-name
        value: manual-test-__9Zi6G8__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __9Zi6G8__(params.pipelines-claim)
            subPath: __9Zi6G8__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__9Zi6G8__(params.job-id)"
          - name: pipelines-claim
            value: "__9Zi6G8__(params.pipelines-claim)"
          - name: env
            value: "__9Zi6G8__{ENV}"
          - name: promotion-name
            value: "__9Zi6G8__(params.promotion-name)"
          - name: env-version
            value: "__9Zi6G8__(params.env-version)"
          - name: repo-full-name
            value: "__9Zi6G8__(params.repo-full-name)"
          - name: repo-ref
            value: "__9Zi6G8__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__9Zi6G8__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __9Zi6G8__(params.manifest-repo-url)
          - name: deploy-image-names
            value: "__9Zi6G8__{DEPLOY_IMAGE_NAMES}"
          - name: deploy-image-tag-pattern
            value: "__9Zi6G8__{DEPLOY_IMAGE_TAG_PATTERN}"
          - name: git-server-http
            value: __9Zi6G8__(params.git-server-http)
          - name: issue-id
            value: "__9Zi6G8__(params.issue-id)"
      EOFEOFEOFEOF
      sed -i '/__9Zi6G8__/s/__9Zi6G8__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __4hHakd__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __4hHakd__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__4hHakd__/s/__4hHakd__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      IMAGE_BUILD_TASK_TEMPLATE="image-build-task-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__pzfS2n__1  #存储项目中资源配置
      shift
      
      pipelineDir=__pzfS2n__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__pzfS2n__1
        if egrep "^ +taskSpec:" __pzfS2n__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__pzfS2n__1
        
        local pipelineName=__pzfS2n__(basename __pzfS2n__configFile) \\
           && pipelineName=__pzfS2n__{configFile#*pipeline.promotion-} \\
           && pipelineName=__pzfS2n__{pipelineName%.yaml*}
        
        local branchPattern=__pzfS2n__(sed -nr '/^branchPattern: .+__pzfS2n__/ {s/^branchPattern: (.+)__pzfS2n__/\\1/p;q}' __pzfS2n__{configFile})
        if test -z "__pzfS2n__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__pzfS2n__{PROMOTION_NAME}/__pzfS2n__{pipelineName}/" \\
            -e "s/\\__pzfS2n__{BRANCH_PATTERN}/__pzfS2n__{branchPattern}/" \\
            __pzfS2n__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __pzfS2n__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __pzfS2n__{output}
        
        local configFile=__pzfS2n__1
        
        local TEMP_PREFIX="__pzfS2n__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __pzfS2n__{configFile} __pzfS2n__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __pzfS2n__{TEMP_PREFIX}*; do
          local task=__pzfS2n__(getTaskType __pzfS2n__file)
          case __pzfS2n__task in
            image-build ) imageBuildTask __pzfS2n__file;;
            env-deploy ) envDeployTask __pzfS2n__file;;
            manual-test ) manualTestTask __pzfS2n__file;;
            env-release ) envReleaseTask __pzfS2n__file;;
            * ) commonTask __pzfS2n__file;;
          esac
        done
        
        rm __pzfS2n__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__pzfS2n__1
        
        if grep "^finally:" 2>&1 >/dev/null __pzfS2n__{configFile}; then
          echo "  finally:" >> __pzfS2n__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__pzfS2n__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __pzfS2n__{configFile} __pzfS2n__{TEMP_PREFIX} finally
        
        local file=""
        for file in __pzfS2n__{TEMP_PREFIX}*; do
          local task=__pzfS2n__(getTaskType __pzfS2n__file)
          case __pzfS2n__task in
            image-build ) return 1;;
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __pzfS2n__file;;
            * ) commonTask __pzfS2n__file;;
          esac
        done
        
        rm __pzfS2n__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__pzfS2n__1
        local tempPreifx=__pzfS2n__2
        local section=__pzfS2n__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__pzfS2n__line"|grep ^- 2>&1 >/dev/null; then
            i=__pzfS2n__(( __pzfS2n__i + 1 ))
            file=__pzfS2n__{tempPreifx}__pzfS2n__i
            touch __pzfS2n__file
          fi
          echo "__pzfS2n__line" >> __pzfS2n__{file}
        done <<EOF
      __pzfS2n__(sed -nr "/^__pzfS2n__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __pzfS2n__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__pzfS2n__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __pzfS2n__{taskFile}
      }
      function getContent() {
        local file=__pzfS2n__1
        local key=__pzfS2n__2
        
        local hasKey=__pzfS2n__3
        local args=
        if test "__pzfS2n__hasKey" == "true"; then
          args="/^  __pzfS2n__key:/{p;d} /^- __pzfS2n__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __pzfS2n__key:/,/^  [a-zA-Z0-9]/{__pzfS2n__args /^  [- ]/p}" __pzfS2n__file
      }
      function getValue() {
        local file=__pzfS2n__1
        local name=__pzfS2n__2
        local prefix="__pzfS2n__3"
        sed -nr "/^__pzfS2n__{prefix}- name: __pzfS2n__{name}/,/^__pzfS2n__{prefix}[^ ]/ {
          /^__pzfS2n__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__pzfS2n__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__pzfS2n__{prefix}    / {
            s/^__pzfS2n__{prefix}  (.*)/\\1/p;
          }
        }" __pzfS2n__{file}
      }
      function addValue() {
        local taskFile=__pzfS2n__1
        local prefix=__pzfS2n__2
        local name=__pzfS2n__3
        local value=__pzfS2n__4
        sed -i "/^__pzfS2n__{prefix}params:/a\\\\__pzfS2n__{prefix}- name: __pzfS2n__{name}\\n__pzfS2n__{prefix}  value: __pzfS2n__{value}" __pzfS2n__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__pzfS2n__1
        if getContent __pzfS2n__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __pzfS2n__{taskFile} \\
        | awk '{print "  "__pzfS2n__0}' >> __pzfS2n__{output}
      }
      
      function imageBuildTask() {
        deployedTaskByTemplate __pzfS2n__1 __pzfS2n__{IMAGE_BUILD_TASK_TEMPLATE}
      }
      function envReleaseTask() {
        deployedTaskByTemplate __pzfS2n__1 __pzfS2n__{ENV_RELEASE_TASK_TEMPLATE}
      }
      function envDeployTask() {
        deployedTaskByTemplate __pzfS2n__1 __pzfS2n__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      function manualTestTask() {
        deployedTaskByTemplate __pzfS2n__1 __pzfS2n__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTaskByTemplate() {
        local taskFile=__pzfS2n__1
        local templateFile=__pzfS2n__2
        
        local name=__pzfS2n__(getContent __pzfS2n__{taskFile} name true)
        local innerPipelineRunName=__pzfS2n__{name#*: }
        
        echo "__pzfS2n__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __pzfS2n__{output}
        getContent __pzfS2n__{taskFile} runAfter true | awk '{print "  "__pzfS2n__0}' >> __pzfS2n__{output}
        
        local env=__pzfS2n__(getValue __pzfS2n__{taskFile} env "  ")
        local deployImageNames=__pzfS2n__(getValue __pzfS2n__{taskFile} deploy-image-names "  ")
        local deployImageTagPattern='__pzfS2n__(params.repo-ref)'
        sed -e "s/\\__pzfS2n__{INNER_PIPELINE_RUN_NAME}/__pzfS2n__{innerPipelineRunName}/" \\
            -e "s/\\__pzfS2n__{ENV}/__pzfS2n__{env}/" \\
            -e "s/\\__pzfS2n__{DEPLOY_IMAGE_NAMES}/__pzfS2n__{deployImageNames}/" \\
            -e "s/\\__pzfS2n__{DEPLOY_IMAGE_TAG_PATTERN}/__pzfS2n__{deployImageTagPattern}/" \\
            __pzfS2n__{templateFile} \\
        | awk '{print "    "__pzfS2n__0}' >> __pzfS2n__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __pzfS2n__{pipelineDir} -p
      
      for file in __pzfS2n__(find __pzfS2n__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__pzfS2n__{pipelineDir}/__pzfS2n__(basename __pzfS2n__file)
        
        validateConfig __pzfS2n__file
      
        pipelineHeader __pzfS2n__file
      
        pipelineTasks __pzfS2n__file
        
        pipelineFinally __pzfS2n__file
      done
      EOFEOFEOFEOF
      sed -i '/__pzfS2n__/s/__pzfS2n__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output
      $kubectl apply -f ~/output
