apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promotion-config-convert
spec:
  params:
  - name: url
    default: https://kubernetes.default
  - name: scan-path
    description: 扫描指定目录内配置
    default: ""
  - name: repo-branch
    description: git仓库分支
  - name: expect-branch
    description: 期望git仓库分支, 仅为期望分支时生成pipeline
    default: master
  workspaces:
  - name: resources
    description: 存储资源, 将扫描其内配置
    readOnly: true
  steps:
  - name: build
    image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent 
    script: |
      url=$(params.url)
      ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      kubectl="kubectl -s=$url --certificate-authority=$ca --token=$token -n $namespace"
      
      
      if test "$(params.repo-branch)" != "$(params.expect-branch)"; then
        exit
      fi
      
      mkdir ~/script -p && cd ~/script
      cat <<EOFEOFEOFEOF > env-deploy-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__ihmBdK__(params.job-id)"
      - name: generate-name
        value: env-deploy-__ihmBdK__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: env-deploy
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __ihmBdK__(params.pipelines-claim)
            subPath: __ihmBdK__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__ihmBdK__(params.job-id)"
          - name: pipelines-claim
            value: "__ihmBdK__(params.pipelines-claim)"
          - name: env
            value: "__ihmBdK__{ENV}"
          - name: promotion-name
            value: "__ihmBdK__(params.promotion-name)"
          - name: env-version
            value: "__ihmBdK__(params.env-version)"
          - name: repo-full-name
            value: "__ihmBdK__(params.repo-full-name)"
          - name: repo-ref
            value: "__ihmBdK__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__ihmBdK__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __ihmBdK__(params.manifest-repo-url)
          - name: git-server-http
            value: __ihmBdK__(params.git-server-http)
          - name: issue-id
            value: "__ihmBdK__(params.issue-id)"
      - name: return-task
        value: env-lock-name
      EOFEOFEOFEOF
      sed -i '/__ihmBdK__/s/__ihmBdK__/$/g' env-deploy-task-template.yaml
      cat <<EOFEOFEOFEOF > env-release-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: env-release
      params:
      - name: job-id
        value: "__RapeIO__(params.job-id)"
      - name: env
        value: __RapeIO__{ENV}
      - name: promotion-name
        value: "__RapeIO__(params.promotion-name)"
      - name: env-version
        value: "__RapeIO__(params.env-version)"
      EOFEOFEOFEOF
      sed -i '/__RapeIO__/s/__RapeIO__/$/g' env-release-task-template.yaml
      cat <<EOFEOFEOFEOF > image-build-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: image-build
      params:
      - name: dest-prefix
        value: 10.1.40.43:5000/__BtRrE1__(params.repo-full-name)/
      - name: dest-suffix
        value: ":__BtRrE1__(params.repo-ref)"
      - name: insecure-registry
        value: 10.1.40.43:5000
      workspaces:
      - name: source
        workspace: pipeline
        subPath: temporary/project-repo
      EOFEOFEOFEOF
      sed -i '/__BtRrE1__/s/__BtRrE1__/$/g' image-build-task-template.yaml
      cat <<EOFEOFEOFEOF > manual-test-task-template.yaml
      taskRef:
        kind: ClusterTask
        name: pipelinerun-apply
      params:
      - name: span-id
        value: "__TOzyat__(params.job-id)"
      - name: generate-name
        value: manual-test-__TOzyat__{INNER_PIPELINE_RUN_NAME}
      - name: spec
        value: |
          pipelineRef:
            name: manual-test
          serviceAccountName: pipeline
          workspaces:
          - name: pipeline 
            persistentVolumeClaim:
              claimName: __TOzyat__(params.pipelines-claim)
            subPath: __TOzyat__(params.job-id)
          - name: gitea-user-token
            secret:
              SecretName: gitea-user-token
          params:
          - name: job-id
            value: "__TOzyat__(params.job-id)"
          - name: pipelines-claim
            value: "__TOzyat__(params.pipelines-claim)"
          - name: env
            value: "__TOzyat__{ENV}"
          - name: promotion-name
            value: "__TOzyat__(params.promotion-name)"
          - name: env-version
            value: "__TOzyat__(params.env-version)"
          - name: repo-full-name
            value: "__TOzyat__(params.repo-full-name)"
          - name: repo-ref
            value: "__TOzyat__(params.repo-ref)"
          - name: manifest-repo-full-name
            value: "__TOzyat__(params.manifest-repo-full-name)"
          - name: manifest-repo-url
            value: __TOzyat__(params.manifest-repo-url)
          - name: git-server-http
            value: __TOzyat__(params.git-server-http)
          - name: issue-id
            value: "__TOzyat__(params.issue-id)"
      EOFEOFEOFEOF
      sed -i '/__TOzyat__/s/__TOzyat__/$/g' manual-test-task-template.yaml
      cat <<EOFEOFEOFEOF > promotion-pipeline-header-template.yaml
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: __r1hP9D__{PROMOTION_NAME}
        labels:
          promotion-pipelines/custom-config: "true"
        annotations:
          promotion-pipelines/branch-pattern: __r1hP9D__{BRANCH_PATTERN}
      spec:
        params:
        - name: job-id
          description: 任务ID,串联起所有子流水线
        - name: pipelines-claim
          description: pipelines-pvc claim, 用于传递给启动的pipelinerun
      
        - name: promotion-name
          description: promotion name
        - name: env-version
          description: env version, 用于关联具体env
          
        - name: repo-full-name
          description: git仓库名称, 用于执行gitea请求 (创建工单,评论)
        - name: repo-branch
          description: git仓库分支
        - name: repo-ref
          description: git仓库SHA
        - name: repo-url
          description: git仓库URL
          
        - name: manifest-repo-full-name
          description: 资源仓库名称
        - name: manifest-repo-url
          description: 资源仓库URL
      
        - name: git-server-http
          description: git server host (如:http://localhost:30280)
        - name: issue-id
          description: 工单ID, 用以与用户交互
      
        workspaces:
        - name: pipeline
          description: 流水线数据目录
      EOFEOFEOFEOF
      sed -i '/__r1hP9D__/s/__r1hP9D__/$/g' promotion-pipeline-header-template.yaml
      cat <<EOFEOFEOFEOF > convert.sh
      PROMOTION_PIPELINE_HEADER_TEMPLATE="promotion-pipeline-header-template.yaml"
      IMAGE_BUILD_TASK_TEMPLATE="image-build-task-template.yaml"
      ENV_DEPLOY_TASK_TEMPLATE="env-deploy-task-template.yaml"
      ENV_RELEASE_TASK_TEMPLATE="env-release-task-template.yaml"
      MANUAL_TEST_TASK_TEMPLATE="manual-test-task-template.yaml"
      
      configDir=__hURgSn__1  #存储项目中资源配置
      shift
      
      pipelineDir=__hURgSn__1  #pipeline输出目录
      shift
      output="" #存储生成的pipeline文件
      
      tmpDir="./"  #存储临时文件
      
      #-----------------------------------------------------
      
      function validateConfig() {
        local configFile=__hURgSn__1
        if egrep "^ +taskSpec:" __hURgSn__{configFile}; then
          echo '[taskSpec] cannot exist !' >&2
          return 1
        fi
      }
      
      #-----------------------------------------------------
      
      function pipelineHeader() {
        local configFile=__hURgSn__1
        
        local pipelineName=__hURgSn__(basename __hURgSn__configFile) \\
           && pipelineName=__hURgSn__{configFile#*pipeline.promotion-} \\
           && pipelineName=__hURgSn__{pipelineName%.yaml*}
        
        local branchPattern=__hURgSn__(sed -nr '/^branchPattern: .+__hURgSn__/ {s/^branchPattern: (.+)__hURgSn__/\\1/p;q}' __hURgSn__{configFile})
        if test -z "__hURgSn__{branchPattern}"; then
          echo '[branchPattern] not specified !' >&2
          return 1
        fi
        
        sed -e "s/\\__hURgSn__{PROMOTION_NAME}/__hURgSn__{pipelineName}/" \\
            -e "s/\\__hURgSn__{BRANCH_PATTERN}/__hURgSn__{branchPattern}/" \\
            __hURgSn__{PROMOTION_PIPELINE_HEADER_TEMPLATE} >> __hURgSn__{output}
      }
      
      #-----------------------------------------------------
      
      function pipelineTasks() {
        echo "  tasks:" >> __hURgSn__{output}
        
        local configFile=__hURgSn__1
        
        local TEMP_PREFIX="__hURgSn__{tmpDir}/.tmp.pipeline-task-"
        
        splitTasks __hURgSn__{configFile} __hURgSn__{TEMP_PREFIX} tasks
        
        local file=""
        for file in __hURgSn__{TEMP_PREFIX}*; do
          local task=__hURgSn__(getTaskType __hURgSn__file)
          case __hURgSn__task in
            image-build ) imageBuildTask __hURgSn__file;;
            env-deploy ) envDeployTask __hURgSn__file;;
            manual-test ) manualTestTask __hURgSn__file;;
            env-release ) envReleaseTask __hURgSn__file;;
            * ) commonTask __hURgSn__file;;
          esac
        done
        
        rm __hURgSn__{TEMP_PREFIX}* -f
      }
      
      function pipelineFinally() {
        local configFile=__hURgSn__1
        
        if grep "^finally:" 2>&1 >/dev/null __hURgSn__{configFile}; then
          echo "  finally:" >> __hURgSn__{output}
        else
          return 0
        fi
        
        local TEMP_PREFIX="__hURgSn__{tmpDir}/.tmp.pipeline-finally-task-"
        
        splitTasks __hURgSn__{configFile} __hURgSn__{TEMP_PREFIX} finally
        
        local file=""
        for file in __hURgSn__{TEMP_PREFIX}*; do
          local task=__hURgSn__(getTaskType __hURgSn__file)
          case __hURgSn__task in
            image-build ) return 1;;
            env-deploy ) return 1;;
            manual-test ) return 1;;
            env-release ) envReleaseTask __hURgSn__file;;
            * ) commonTask __hURgSn__file;;
          esac
        done
        
        rm __hURgSn__{TEMP_PREFIX}* -f
      }
      
      #-----------------------------------------------------
      
      #拆分tasks到独立文件
      function splitTasks() {
        local configFile=__hURgSn__1
        local tempPreifx=__hURgSn__2
        local section=__hURgSn__3
        
        local i=0
        local file=
        while IFS=~ read line; do
          if echo "__hURgSn__line"|grep ^- 2>&1 >/dev/null; then
            i=__hURgSn__(( __hURgSn__i + 1 ))
            file=__hURgSn__{tempPreifx}__hURgSn__i
            touch __hURgSn__file
          fi
          echo "__hURgSn__line" >> __hURgSn__{file}
        done <<EOF
      __hURgSn__(sed -nr "/^__hURgSn__{section}:/,/^[a-zA-Z0-9]/ {/^[- ]/p}" __hURgSn__{configFile})
      EOF
      }
      
      function getTaskType() {
        local taskFile=__hURgSn__1
        sed -nr '/  taskRef:/,/^  [a-zA-Z0-9]/{/^    name:/s/.*name: (.*)/\\1/p}' __hURgSn__{taskFile}
      }
      function getContent() {
        local file=__hURgSn__1
        local key=__hURgSn__2
        
        local hasKey=__hURgSn__3
        local args=
        if test "__hURgSn__hasKey" == "true"; then
          args="/^  __hURgSn__key:/{p;d} /^- __hURgSn__key:/{s/^-(.*)/ \\1/p;d}"
        fi
        sed -nr "/^[- ] __hURgSn__key:/,/^  [a-zA-Z0-9]/{__hURgSn__args /^  [- ]/p}" __hURgSn__file
      }
      function getValue() {
        local file=__hURgSn__1
        local name=__hURgSn__2
        local prefix="__hURgSn__3"
        sed -nr "/^__hURgSn__{prefix}- name: __hURgSn__{name}/,/^__hURgSn__{prefix}[^ ]/ {
          /^__hURgSn__{prefix}  value: [^|]/ {
            s/^ +value: (.*)/\\1/p;
            q;
          }
          /^__hURgSn__{prefix}  value: |/ {
            s/^ +value: (.*)/\\1/p;
          }
          /^__hURgSn__{prefix}    / {
            s/^__hURgSn__{prefix}  (.*)/\\1/p;
          }
        }" __hURgSn__{file}
      }
      function addValue() {
        local taskFile=__hURgSn__1
        local prefix=__hURgSn__2
        local name=__hURgSn__3
        local value=__hURgSn__4
        sed -i "/^__hURgSn__{prefix}params:/a\\\\__hURgSn__{prefix}- name: __hURgSn__{name}\\n__hURgSn__{prefix}  value: __hURgSn__{value}" __hURgSn__{taskFile}
      }
      
      function commonTask() {
        local taskFile=__hURgSn__1
        if getContent __hURgSn__{taskFile} taskRef | grep kind: 2>&1 >/dev/null; then
          echo '[kind] cannot be specified in [taskRef] !' >&2
          return 1
        fi
        sed -r '/^  taskRef:/a\\    kind: ClusterTask' __hURgSn__{taskFile} \\
        | awk '{print "  "__hURgSn__0}' >> __hURgSn__{output}
      }
      
      function imageBuildTask() {
        deployedTaskByTemplate __hURgSn__1 __hURgSn__{IMAGE_BUILD_TASK_TEMPLATE}
      }
      function envReleaseTask() {
        deployedTaskByTemplate __hURgSn__1 __hURgSn__{ENV_RELEASE_TASK_TEMPLATE}
      }
      function envDeployTask() {
        deployedTaskByTemplate __hURgSn__1 __hURgSn__{ENV_DEPLOY_TASK_TEMPLATE}
      }
      function manualTestTask() {
        deployedTaskByTemplate __hURgSn__1 __hURgSn__{MANUAL_TEST_TASK_TEMPLATE}
      }
      
      function deployedTaskByTemplate() {
        local taskFile=__hURgSn__1
        local templateFile=__hURgSn__2
        
        local name=__hURgSn__(getContent __hURgSn__{taskFile} name true)
        local innerPipelineRunName=__hURgSn__{name#*: }
        
        echo "__hURgSn__{name}" |  sed -r 's/^ (.*)/  -\\1/' >> __hURgSn__{output}
        getContent __hURgSn__{taskFile} runAfter true | awk '{print "  "__hURgSn__0}' >> __hURgSn__{output}
        
        local env=__hURgSn__(getValue __hURgSn__{taskFile} env "  ")
        sed -e "s/\\__hURgSn__{INNER_PIPELINE_RUN_NAME}/__hURgSn__{innerPipelineRunName}/" \\
            -e "s/\\__hURgSn__{ENV}/__hURgSn__{env}/" \\
            __hURgSn__{templateFile} \\
        | awk '{print "    "__hURgSn__0}' >> __hURgSn__{output}
      }
      
      #-----------------------------------------------------
      set -ex
      
      mkdir __hURgSn__{pipelineDir} -p
      
      for file in __hURgSn__(find __hURgSn__{configDir} -maxdepth 1 -name 'pipeline.promotion-*.yaml'); do
        output=__hURgSn__{pipelineDir}/__hURgSn__(basename __hURgSn__file)
        
        validateConfig __hURgSn__file
      
        pipelineHeader __hURgSn__file
      
        pipelineTasks __hURgSn__file
        
        pipelineFinally __hURgSn__file
      done
      EOFEOFEOFEOF
      sed -i '/__hURgSn__/s/__hURgSn__/$/g' convert.sh
      sh convert.sh '$(workspaces.resources.path)/$(params.scan-path)' ~/output
      $kubectl apply -f ~/output
