apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
secrets:
- name: git-ssh
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-init
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger
